//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : BanHistory.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import hirondelle.date4j.DateTime;


public class BanHistory {
	public int id;
	public String username;
	public String manager;
	public DateTime begin;
	public DateTime end;
}
