//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GameReport.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import hirondelle.date4j.DateTime;


public class GameReport {
	public int tableID;
	public String username;
	public DateTime time;
}
