//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ITransactionInfo.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import casino.cardgame.game_enum.TransactionStatus;
import casino.cardgame.game_enum.TransactionType;
import hirondelle.date4j.DateTime;


public class ITransactionInfo {
	public DateTime getTransactionDate() {
            return null;
	}
	
	public TransactionType getTransactionType() {
	    return null;
	}
	
	public Double getTotalChip() {
	    return null;
	}
	
	public String getTransactionOwnerName() {
	    return null;
	}
	
	public TransactionStatus getTransactionStatus() {
            return null;    
	}
	
	public String getTransactionNote() {
	    return null;
	}
	
	public void setTransactionDate(DateTime date) {
	
	}
	
	public void setTransactionType(casino.cardgame.game_enum.TransactionType type) {
	
	}
	
	public void setTotalChip(Double total) {
	
	}
	
	public void setTransactionOwnerName() {
	
	}
	
	public void setTransactionNote(String note) {
	
	}
	
	public void ITransactionInfo(DateTime date, casino.cardgame.game_enum.TransactionType type, Double chip, String userName, casino.cardgame.game_enum.TransactionStatus status, String note) {
	
	}
}
