//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IUserInfo.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import java.util.Date;
import java.util.List;


public class IUserInfo {
	protected String strUserName;
	protected String strEmail;
	protected String strDisplayName;
	protected Double chip;
	public Double GameChip;
	public List<String> ListFriend;
	public Date LastJoinedDate;
	public Date RegisterDate;
	public Double TotalDeposit;
	public String strUserTitle;
	public String strUserStatus;
	public int TotalPlayedMatch;
	public int TotalWinMatch;
	public int TotalLostMatch;
	public String Location;
}
