//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : LoginHistory.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import java.util.Date;


public class LoginHistory {
	public int id;
	public Date date;
	public String username;
	public String ip;
	public void LoginHistory() {
	
	}
	
	public void LoginHistory(String username, Date date, String ip) {
	
	}
}
