//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : RoomHistory.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import java.util.Date;


public class RoomHistory {
	public int id;
	public String name;
	public Date CreatedDate;
	public String creator;
	public void RoomHistory() {
	
	}
	
	public void RoomHistory(int id, String name, Date created, String creator) {
	
	}
}
