//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : UserInfo.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import com.smartfoxserver.v2.entities.variables.SFSUserVariable;
import com.smartfoxserver.v2.entities.variables.UserVariable;
import hirondelle.date4j.DateTime;
import java.util.ArrayList;
import java.util.List;


public class RoomInfo {
    private String _roomName;
    private String _password;
    private String _displayName;
    private int _maxUsers;
    private Double _minBuyin;
    private Double _maxBuyin;
    private boolean _noLimit;
    private Double _betChip;
    private Double _smallBlind;
    private Double _bigBlind;
    private String _createBy;
    private DateTime _createDate;
    private String _status;
    private Boolean _isPlaying;
    
    public RoomInfo(){
        
    }

    public RoomInfo(String name, String password, String display, int maxUser, Double minChip, Double maxChip, boolean noLimit, Double betChip
            , Double smallBlind, Double bigBlind, String createBy, DateTime createDate, String status, Boolean isPlaying){
                    _roomName = name;
                    _password = password;
                    _displayName = display;
                    _maxUsers = maxUser;
                    _minBuyin = minChip;
                    _maxBuyin = maxChip;
                    _noLimit = noLimit;
                    _betChip = betChip;
                    _smallBlind = smallBlind;
                    _bigBlind = bigBlind;
                    _createDate = createDate;
                    _createBy = createBy;
                    _status = status;
                    _isPlaying = isPlaying;
    }

    public String getPassword() {
        return _password;
    }

    public void setPassword(String password) {
        this._password = password;
    }

    public String getDisplayName() {
        return _displayName;
    }

    public void setDisplayName(String displayName) {
        this._displayName = displayName;
    }

    public int getMaxUsers() {
        return _maxUsers;
    }

    public void setMaxUsers(int maxUsers) {
        this._maxUsers = maxUsers;
    }

    public Double getMinBuyin() {
        return _minBuyin;
    }

    public void setMinBuyin(Double minChip) {
        this._minBuyin = minChip;
    }

    public Double getMaxBuyin() {
        return _maxBuyin;
    }

    public void setMaxBuyin(Double maxChip) {
        this._maxBuyin = maxChip;
    }

    public Double getBetChip() {
        return _betChip;
    }

    public void setBetChip(Double betChip) {
        this._betChip = betChip;
    }

    public Double getSmallBlind() {
        return _smallBlind;
    }

    public void setSmallBlind(Double smallBlind) {
        this._smallBlind = smallBlind;
    }

    public Double getBigBlind() {
        return _bigBlind;
    }

    public void setBigBlind(Double bigBlind) {
        this._bigBlind = bigBlind;
    }

    public String getCreateBy() {
        return _createBy;
    }

    public void setCreateBy(String createBy) {
        this._createBy = createBy;
    }

    public DateTime getCreateDate() {
        return _createDate;
    }

    public void setCreateDate(DateTime createDate) {
        this._createDate = createDate;
    }

    public String getStatus() {
        return _status;
    }

    public void setStatus(String status) {
        this._status = status;
    }

    public Boolean getIsPlaying() {
        return _isPlaying;
    }

    public void setIsPlaying(Boolean isPlaying) {
        this._isPlaying = isPlaying;
    }

    public String getRoomName() {
        return _roomName;
    }

    public void setRoomName(String roomName) {
        this._roomName = roomName;
    }

    public boolean getNoLimit() {
        return _noLimit;
    }

    public void setNoLimit(boolean noLimit) {
        this._noLimit = noLimit;
    }
}
