//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ServerStateHistory.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import java.util.Date;


public class ServerStateHistory {
	public Object FromState;
	public Object ToState;
	public Date date;
	public String strAdminName;
	public String strAdminIP;
	public void ServerStateHistory(Object from, Object to, Date date, String name, String ip) {
	
	}
	
	public void ServerStateHistory() {
	
	}
}
