//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TableResult.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import java.util.Date;


public class TableResult {
	public int id;
	public String username;
	public int TableResultId;
	public int amount;
	public Date CreatedDate;
	public void TableResult() {
	
	}
	
	public void TableResult(int tbId, String username, int amount, Date created) {
	
	}
}
