//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TransactionInfo.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity;

import casino.cardgame.game_enum.TransactionStatus;
import casino.cardgame.game_enum.TransactionType;
import hirondelle.date4j.DateTime;


public class TransactionInfo {
//    private int _id;
//    private DateTime _date;
//    private TransactionType m_type;
//    private Double m_totalChip;
//    private String m_ownerName;
//    private TransactionStatus m_status;
//    private String m_note;
    
    private int _id;
    private String _userName;
    private String _byAdmin;
    private String _type;
    private double _amount;
    private String _date;

    public TransactionInfo(){
        
    }
//    public TransactionInfo(DateTime date, casino.cardgame.game_enum.TransactionType type, Double chip, String userName, casino.cardgame.game_enum.TransactionStatus status, String note) {
//        
//    }

    public int getId() {
        return _id;
    }

    public void setId(int id) {
        this._id = id;
    }

    public String getUserName() {
        return _userName;
    }

    public void setUserName(String userName) {
        this._userName = userName;
    }

    public String getByAdmin() {
        return _byAdmin;
    }

    public void setByAdmin(String byAdmin) {
        this._byAdmin = byAdmin;
    }

    public String getType() {
        return _type;
    }

    public void setType(String type) {
        this._type = type;
    }

    public double getAmount() {
        return _amount;
    }

    public void setAmount(double amount) {
        this._amount = amount;
    }

    public String getDate() {
        return _date;
    }

    public void setDate(String date) {
        this._date = date;
    }

}
