//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : UserInfo.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//
package casino.cardgame.entity;

import com.smartfoxserver.v2.entities.variables.SFSUserVariable;
import com.smartfoxserver.v2.entities.variables.UserVariable;
import hirondelle.date4j.DateTime;
import java.util.ArrayList;
import java.util.List;

public class UserInfo {

    private String strUserName;
    private String strPassWord;
    private String strEmail;
    private String strDisplayName;
    private Double chip;
    private Double TourChip;//Tournament Chip.
    private Double BuyIn;//poker hold'em chip
    private Double GameChip;
    private List<String> ListFriend;
    private DateTime LastJoinedDate;
    private DateTime RegisterDate;
    private Double TotalDeposit;
    private String strUserTitle;
    private String strUserStatus;
    private int TotalPlayedMatch;
    private int TotalWinMatch;
    private int TotalLostMatch;
    private String Location;
    private String avatar;
    private String role;
    private boolean isPlaying;

    public UserInfo() {
    }

    public UserInfo(String name, String password, String mail, String display, Double chip, Double TChip, Double buyIn, Double gameChip,
            DateTime joined, DateTime reg, Double totalDeposit, String title, String status,
            int totalPlayedMatch, int numWin, int numLost, String locate, String ava, String role, List<String> listFriend) {
        strUserName = name;
        strPassWord = password;
        strEmail = mail;
        strDisplayName = display;
        this.chip = chip;
        GameChip = gameChip;
        TourChip = TChip;
        BuyIn = buyIn;
        ListFriend = listFriend;
        LastJoinedDate = joined;
        RegisterDate = reg;
        TotalDeposit = totalDeposit;
        strUserTitle = title;
        strUserStatus = status;
        TotalPlayedMatch = totalPlayedMatch;
        TotalWinMatch = numWin;
        TotalLostMatch = numLost;
        Location = locate;
        avatar = ava;
        this.role = role;
    }

    public UserInfo(String userName, String password, String email, String displayName, Double chip, Double tourChip, Double buyIn, int i, Object object, Object object0, int i0, String title, String status, int i1, int i2, int i3, String location, String avartar, Object object1) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * @return the strUserName
     */
    public String getUserName() {
        return strUserName;
    }

    /**
     * @param strUserName the strUserName to set
     */
    public void setUserName(String strUserName) {
        this.strUserName = strUserName;
    }

    /**
     * @return the strEmail
     */
    public String getEmail() {
        return strEmail;
    }

    /**
     * @param strEmail the strEmail to set
     */
    public void setEmail(String strEmail) {
        this.strEmail = strEmail;
    }

    /**
     * @return the strDisplayName
     */
    public String getDisplayName() {
        return strDisplayName;
    }

    /**
     * @param strDisplayName the strDisplayName to set
     */
    public void setDisplayName(String strDisplayName) {
        this.strDisplayName = strDisplayName;
    }

    /**
     * @return the chip
     */
    public Double getChip() {
        return chip;
    }

    /**
     * @param chip the chip to set
     */
    public void setChip(Double chip) {
        this.chip = chip;
    }

    /**
     * @return the GameChip
     */
    public Double getGameChip() {
        return GameChip;
    }

    /**
     * @param GameChip the GameChip to set
     */
    public void setGameChip(Double GameChip) {
        this.GameChip = GameChip;
    }

    /**
     * @return the ListFriend
     */
    public List<String> getListFriend() {
        return ListFriend;
    }

    /**
     * @param ListFriend the ListFriend to set
     */
    public void setListFriend(List<String> ListFriend) {
        this.ListFriend = ListFriend;
    }

    /**
     * @return the LastJoinedDate
     */
    public DateTime getLastJoinedDate() {
        return LastJoinedDate;
    }

    /**
     * @param LastJoinedDate the LastJoinedDate to set
     */
    public void setLastJoinedDate(DateTime LastJoinedDate) {
        this.LastJoinedDate = LastJoinedDate;
    }

    /**
     * @return the RegisterDate
     */
    public DateTime getRegisterDate() {
        return RegisterDate;
    }

    /**
     * @param RegisterDate the RegisterDate to set
     */
    public void setRegisterDate(DateTime RegisterDate) {
        this.RegisterDate = RegisterDate;
    }

    /**
     * @return the TotalDeposit
     */
    public Double getTotalDeposit() {
        return TotalDeposit;
    }

    /**
     * @param TotalDeposit the TotalDeposit to set
     */
    public void setTotalDeposit(Double TotalDeposit) {
        this.TotalDeposit = TotalDeposit;
    }

    /**
     * @return the strUserTitle
     */
    public String getUserTitle() {
        return strUserTitle;
    }

    /**
     * @param strUserTitle the strUserTitle to set
     */
    public void setUserTitle(String strUserTitle) {
        this.strUserTitle = strUserTitle;
    }

    /**
     * @return the strUserStatus
     */
    public String getUserStatus() {
        return strUserStatus;
    }

    /**
     * @param strUserStatus the strUserStatus to set
     */
    public void setUserStatus(String strUserStatus) {
        this.strUserStatus = strUserStatus;
    }

    /**
     * @return the TotalPlayedMatch
     */
    public int getTotalPlayedMatch() {
        return TotalPlayedMatch;
    }

    /**
     * @param TotalPlayedMatch the TotalPlayedMatch to set
     */
    public void setTotalPlayedMatch(int TotalPlayedMatch) {
        this.TotalPlayedMatch = TotalPlayedMatch;
    }

    /**
     * @return the TotalWinMatch
     */
    public int getTotalWinMatch() {
        return TotalWinMatch;
    }

    /**
     * @param TotalWinMatch the TotalWinMatch to set
     */
    public void setTotalWinMatch(int TotalWinMatch) {
        this.TotalWinMatch = TotalWinMatch;
    }

    /**
     * @return the TotalLostMatch
     */
    public int getTotalLostMatch() {
        return TotalLostMatch;
    }

    /**
     * @param TotalLostMatch the TotalLostMatch to set
     */
    public void setTotalLostMatch(int TotalLostMatch) {
        this.TotalLostMatch = TotalLostMatch;
    }

    /**
     * @return the Location
     */
    public String getLocation() {
        return Location;
    }

    /**
     * @param Location the Location to set
     */
    public void setLocation(String Location) {
        this.Location = Location;
    }

    /**
     * @author: thongth Convert a UserInfo to list of UserVariable
     */
    public List<UserVariable> ToUserVariables() {
        List<UserVariable> userVars = new ArrayList<UserVariable>();

//        userVars.add( new SFSUserVariable("strUserName", strUserName));
//        userVars.add( new SFSUserVariable("strEmail", strEmail));
        userVars.add(new SFSUserVariable("strDisplayName", strDisplayName));
        userVars.add(new SFSUserVariable("avatar", avatar));
        userVars.add(new SFSUserVariable("chip", chip));
//        userVars.add( new SFSUserVariable("GameChip", GameChip));
//        userVars.add( new SFSUserVariable("ListFriend", ListFriend));
//        userVars.add( new SFSUserVariable("LastJoinedDate", LastJoinedDate));
//        userVars.add( new SFSUserVariable("RegisterDate", RegisterDate));
//        userVars.add( new SFSUserVariable("TotalDeposit", TotalDeposit));
//        userVars.add( new SFSUserVariable("strUserTitle", strUserTitle));
//        userVars.add( new SFSUserVariable("strUserStatus", strUserStatus));
//        userVars.add( new SFSUserVariable("TotalPlayedMatch", TotalPlayedMatch));
//        userVars.add( new SFSUserVariable("TotalWinMatch", TotalWinMatch));
//        userVars.add( new SFSUserVariable("TotalLostMatch", TotalLostMatch));
//        userVars.add( new SFSUserVariable("Location", Location));

        return userVars;
    }

    public Double getBuyIn() {
        return BuyIn;
    }

    public void setBuyIn(Double BuyIn) {
        this.BuyIn = BuyIn;
    }

    public Double getTourChip() {
        return TourChip;
    }

    public void setTourChip(Double TourChip) {
        this.TourChip = TourChip;
    }

    public String getPassWord() {
        return strPassWord;
    }

    public void setPassWord(String strPassWord) {
        this.strPassWord = strPassWord;
    }

    public String getAvartar() {
        return avatar;
    }

    public void setAvartar(String avartar) {
        this.avatar = avartar;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public boolean isIsPlaying() {
        return isPlaying;
    }

    public void setIsPlaying(boolean isPlaying) {
        this.isPlaying = isPlaying;
    }
}
