//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : DeskState.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity;


public enum DeskState {
        //Đang Chơi
	PLAYING,
        //Ngừng chơi (bỏ cuộc, thoát game ...)
	STOP_PLAYING,
        //Đợi đến lượt, spectator
	WAITING,
        //Đăng ký trước ở đó, khi nào chơi sẽ chuyển về waiting
        //Tạm chưa dùng trong tá lả ( dùng trong poker hoặc nâng cấp về sau)
        SIT_ON,
        //Ghế Trống
	EMPTY,
        
        //khoatd: đã sẵn sàng chờ bắt đầu game
        READY
        
}
