//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ICardHand.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//  @ Desc: Danh sách các lá bài trong tay user và lá bài trên bàn user(đã sử dụng)
//          User card collection
//



package casino.cardgame.entity.game_entity;

import java.util.List;


public interface ICardHand {
        
        public enum COMPARE{ WIN, LOOSE, DRAW};
	public List<ICard> getCurrentHand();	
        public boolean IsContain(ICard card);
        public boolean IsContain(int cardId);
        public boolean AddToCurrentHand(int cardId);
        public boolean AddToCurrentHand(ICard card);
        public boolean AddToCurrentHand(List<ICard> listCard);
        public boolean AddToCurrentHand2(List<Integer> listCard);
        
        public ICard RemoveACardInHand(int cardId);
        public ICard RemoveACardInHand(ICard card);        
        public ICard RemoveLastCard();
        
	public void setCurrentHand(List<ICard> hand) ;	
	public COMPARE compare(ICardHand hand) ;		
        public String getHandType();
        public String getHandType(List<ICard> hand);
        public String getHandType2(List<Integer> handId);
        
}
