//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ICard.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity;


public interface ICard {
    public enum CardCompare{
        GREATER,        // Xì  vs K
        SAME_GREATER,   // Xì Cơ vs Xì Rô
        SAME_LOWER,     // Xì Rô vs Xì cơ
        SAME_SAME,      // Xì Rô vs Xì Rô (trường hợp ko xảy ra trong cùng 1 bộ bài )
        LOWER           // K vs Xì
    }
	public int getCardId() ;
	
	public String getCardName();
	
	public int getCardValue() ;
	
	public CardCompare compare(ICard card);
}
