//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IListCards.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//  @ Desc: Table Card Collection
//



package casino.cardgame.entity.game_entity;

import java.util.List;


public interface IListCards {
	public List<ICard> getCurrentList() ;	
	public void renew() ;	
	public ICard getNextCard() ;	
        public List<ICard> getNextCard(int number);        
	public void shuffleListCard() ;	
	public int getCurrentLengh();
}
