//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.game.tala;

import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Timer;


public class GetPlayerCardRequest extends casino.cardgame.message.request.SFSGameRequest {
    
    private String m_fromUser;
    private int m_cardId;
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        setM_fromUser(isfso.getUtfString("from_user"));
        setM_cardId((int) isfso.getInt("card_id"));
        return this;
    }

    @Override
    public String GetRequestName() {
        return TALA_REQUEST_NAME.GET_PLAYER_CARD;
    }

    public String getM_fromUser() {
        return m_fromUser;
    }

    public void setM_fromUser(String m_fromUser) {
        this.m_fromUser = m_fromUser;
    }

    public int getM_cardId() {
        return m_cardId;
    }

    public void setM_cardId(int m_cardId) {
        this.m_cardId = m_cardId;
    }
}
