//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ShowCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//  @ Desc: Request to show (list of card) to other - Hạ Bài/ Hạ Phỏm
package casino.cardgame.message.request.game.tala;

import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import com.smartfoxserver.v2.entities.data.SFSArray;
import java.util.ArrayList;

public class ShowCardRequest extends casino.cardgame.message.request.SFSGameRequest {
    //Danh sách card sẽ show.
    //m_listCard.size() = số phỏm hạ
    //m_listCard.getItemAt(index) = Danh sách phỏm hạ ( cần kiểm tra người dùng có hạ đúng ko ?)
    //Nếu không -> người dùng hack do đã kiểm tra ở client, -> Xử lí người dùng:
    // -> Xử lí thua tương tự như thoát game
    // -> Xử lí banned hoặc .... nếu cần

    private ArrayList<Integer> m_listCard;
    public static String LIST_CARD = "list_card";

    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {   
        m_listCard = new ArrayList<Integer>();
        SFSArray sfsArray = (SFSArray)isfso.getSFSArray(LIST_CARD);
        for(int i = 0; i< sfsArray.size(); i++){
            m_listCard.add(sfsArray.getInt(i));
        }
        return this;
    }

    @Override
    public String GetRequestName() {
        return TALA_REQUEST_NAME.SHOW_CARD;
    }

    /**
     * @return the m_listCard
     */
    public ArrayList<Integer> getM_listCard() {
        return m_listCard;
    }
}
