//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TALA_REQUEST_NAME.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.request.game.tala;


public class TALA_REQUEST_NAME {
	public static String GET_PLAYER_CARD = "get_player_card_req";
	public static String GET_NEXT_CARD = "get_next_card_req";
	public static String SHOW_CARD = "show_card_req";
	public static String REMOVE_CARD = "remove_card_req";
	public static String LEAVE_GAME = "leave_game_req";
        public static String CONFIRM_READY_GAME = "confirm_ready_game_req";
}
