//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Turn.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : Send turn time to player
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_DenBai extends casino.cardgame.message.reponse.SFSGameReponse {

    protected String m_username;
    private String m_fromName;
    private double m_giveBackChip;
    private double m_subtractChip;

    public Notify_DenBai() {
        super(TALA_REPONSE_NAME.DEN_BAI_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", m_username);
        obj.putUtfString("from_name", m_fromName);
        obj.putDouble("give_back_chip", getM_giveBackChip());
        obj.putDouble("subtract_chip", getM_subtractChip());
        return obj;
    }

    public String getM_username() {
        return m_username;
    }

    public Notify_DenBai setM_username(String m_username) {
        this.m_username = m_username;
        return this;
    }

    public String getM_fromName() {
        return m_fromName;
    }

    public Notify_DenBai setM_fromName(String m_fromUser) {
        this.m_fromName = m_fromUser;
        return this;
    }

    public double getM_giveBackChip() {
        return m_giveBackChip;
    }

    public Notify_DenBai setM_giveBackChip(double m_giveBackChip) {
        this.m_giveBackChip = m_giveBackChip;
        return this;
    }

    public double getM_subtractChip() {
        return m_subtractChip;
    }

    public Notify_DenBai setM_subtractChip(double m_subtractChip) {
        this.m_subtractChip = m_subtractChip;
        return this;
    }
}
