//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_GameResult.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_LooseGame extends casino.cardgame.message.reponse.SFSGameReponse {

    private String m_looseName;
    
    public Notify_LooseGame() {
        super(TALA_REPONSE_NAME.LOOSE_GAME);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", getM_looseName());
        return obj;
    }

    /**
     * @return the m_looseName
     */
    public String getM_looseName() {
        return m_looseName;
    }

    /**
     * @param m_looseName the m_looseName to set
     */
    public void setM_looseName(String m_looseName) {
        this.m_looseName = m_looseName;
    }
}
