//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_KickUser extends casino.cardgame.message.reponse.SFSGameReponse {

    //Notify_KickUser is used in 2 cases:
    //	1: user not ready in prestart game.
    //	2: user don't have enought money to play game.(after finish game).
		
    private int m_resType; 
    
    public Notify_KickUser() {
        super(TALA_REPONSE_NAME.KICK_USER_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putInt("response_type", getM_resType());
        return obj;
    }

    /**
     * @return the m_resType
     */
    public int getM_resType() {
        return m_resType;
    }

    /**
     * @param m_resType the m_resType to set
     */
    public void setM_resType(int m_resType) {
        this.m_resType = m_resType;
    }
}
