//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_Start extends casino.cardgame.message.reponse.SFSGameReponse {

    protected ArrayList<Integer> m_listCard;
    protected String m_holderName;
    private int m_time;

    public Notify_Start() {
        super(TALA_REPONSE_NAME.START);
    }

    public String getM_holderName() {
        return m_holderName;
    }

    public ArrayList<Integer> getM_listCard() {
        return m_listCard;
    }

    public void setM_holderName(String m_holderName) {
        this.m_holderName = m_holderName;
    }

    public void setM_listCard(ArrayList<Integer> m_listCard) {
        this.m_listCard = m_listCard;
    }
    public void setM_time(int m_time) {
        this.m_time = m_time;
    }
    
    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("holder_name", m_holderName);
        obj.putIntArray("list_card", m_listCard);
        obj.putInt("time", m_time);
        return obj;
    }
}
