//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_EndGame.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_EndGame extends casino.cardgame.message.reponse.SFSGameReponse {
    private String m_userName;
    private int m_time;
    
    public Notify_EndGame() {
        super(TALA_REPONSE_NAME.END_GAME);
    }
     public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", getM_userName());
        obj.putDouble("time", getM_time());
        return obj;
    }

    public String getM_userName() {
        return m_userName;
    }

    public Notify_EndGame setM_userName(String m_userName) {
        this.m_userName = m_userName;
        return this;
    }
    public int getM_time() {
        return m_time;
    }
    public Notify_EndGame setM_time(int m_time) {
        this.m_time = m_time;
        return this;
    }
}
