//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_GameResult.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_GameResult extends casino.cardgame.message.reponse.SFSGameReponse {

    protected ArrayList<String> m_listUserName;
    protected ArrayList< ArrayList<Integer>> m_listUserCard;
    protected ArrayList<Integer> m_listCoinResult;

    public Notify_GameResult() {
        super(TALA_REPONSE_NAME.GAME_RESULT);
    }

    public ArrayList<Integer> getM_listCoinResult() {
        return m_listCoinResult;
    }

    public ArrayList<ArrayList<Integer>> getM_listUserCard() {
        return m_listUserCard;
    }

    public void setM_listCoinResult(ArrayList<Integer> m_listCoinResult) {
        this.m_listCoinResult = m_listCoinResult;
    }

    public void setM_listUserCard(ArrayList<ArrayList<Integer>> m_listUserCard) {
        this.m_listUserCard = m_listUserCard;
    }

    public void setM_listUserName(ArrayList<String> m_listUserName) {
        this.m_listUserName = m_listUserName;
    }

    public ArrayList<String> getM_listUserName() {
        return m_listUserName;
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfStringArray("list_username", m_listUserName);

        SFSArray sfsArr = new SFSArray();
        for (ArrayList<Integer> arrInt : m_listUserCard) {
            SFSArray arr = new SFSArray();
            
            for (Integer card : arrInt) {
                arr.addInt(card);
            }
            
            sfsArr.addSFSArray(arr);
        }
        obj.putSFSArray("list_user_card", sfsArr);

        obj.putIntArray("list_coin_result", m_listCoinResult);
        return obj;
    }
}
