//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Finish.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_Finish extends casino.cardgame.message.reponse.SFSGameReponse {

    protected ArrayList<ArrayList<Integer>> m_listCard;
    protected ArrayList<Integer> m_listResult;
    protected ArrayList<String> m_listUserName;
    protected ArrayList<Double> m_listChip;

    public Notify_Finish() {
        super(TALA_REPONSE_NAME.FINISH);
    }

    public ArrayList<ArrayList<Integer>> getM_listCard() {
        return m_listCard;
    }

    public ArrayList<Double> getM_listChip() {
        return m_listChip;
    }

    public ArrayList<String> getM_listUserName() {
        return m_listUserName;
    }

    public Notify_Finish setM_listCard(ArrayList<ArrayList<Integer>> m_listCard) {
        this.m_listCard = m_listCard;
        return this;
    }

    public Notify_Finish setM_listChip(ArrayList<Double> m_listChip) {
        this.m_listChip = m_listChip;
        return this;
    }

    public Notify_Finish setM_listUserName(ArrayList<String> m_listUserName) {
        this.m_listUserName = m_listUserName;
        return this;
    }

    public ArrayList<Integer> getM_listResult() {
        return m_listResult;
    }
    public Notify_Finish setM_listResult(ArrayList<Integer> m_listResult) {
        this.m_listResult = m_listResult;
        return this;
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfStringArray("list_username", m_listUserName);
        obj.putDoubleArray("list_chip", m_listChip);
        obj.putIntArray("list_result", m_listResult);

        SFSArray sfsArr = new SFSArray();
        for (int i = 0; i< m_listCard.size(); i++) {
            ArrayList<Integer> arrCardId = m_listCard.get(i);
            SFSArray arr = new SFSArray();

            for (Integer card : arrCardId) {
                arr.addInt(card);
            }

            sfsArr.addSFSArray(arr);
        }
        obj.putSFSArray("list_card", sfsArr);

//        SFSArray sfsListResult = new SFSArray();
//        for (int i = 0; i< m_listResult.size(); i++) {
//            sfsListResult.addInt(m_listResult.get(i));
//        }
//        obj.putSFSArray("list_result", sfsArr);
        
        return obj;
    }
}
