//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Turn.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : Send turn time to player
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_Turn extends casino.cardgame.message.reponse.SFSGameReponse {

    protected String m_username;
    protected int m_time;

    public Notify_Turn() {
        super(TALA_REPONSE_NAME.TURN);
    }

    public int getM_time() {
        return m_time;
    }

    public String getM_username() {
        return m_username;
    }

    public void setM_time(int m_time) {
        this.m_time = m_time;
    }

    public void setM_username(String m_username) {
        this.m_username = m_username;
    }
    
    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", m_username);
        obj.putInt("time", m_time);
        return obj;
    }
}
