//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_UserAction.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_UserAction extends casino.cardgame.message.reponse.SFSGameReponse {

    protected String m_username;
    protected int m_cardId;

    public Notify_UserAction() {
        super(TALA_REPONSE_NAME.USER_ACTION);
    }

    public int getM_cardId() {
        return m_cardId;
    }

    public String getM_username() {
        return m_username;
    }

    public Notify_UserAction setM_cardId(int m_cardId) {
        this.m_cardId = m_cardId;
        return this;
    }

    public Notify_UserAction setM_username(String m_username) {
        this.m_username = m_username;
        return this;
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", m_username);
        obj.putInt("card_id", m_cardId);
        return obj;
    }
}
