//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_PreStart.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : Broadcast ready time to all players in game board
//
//
package casino.cardgame.message.reponse.game.tala;

import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_PreStart extends casino.cardgame.message.reponse.SFSGameReponse {

    //khoatd: m_isPrestart = false: vì lý do ko đủ người,... -> client chuyển về màn hình waiting
    private boolean m_isPrestart;
    protected int m_time;

    public Notify_PreStart() {
        super(TALA_REPONSE_NAME.PRE_START);
    }
    
    public Notify_PreStart setM_time(int m_time) {
        this.m_time = m_time;
        return this;
    }

    public int getM_time() {
        return m_time;
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putBool("is_prestart", m_isPrestart);
        obj.putInt("time", m_time);
        return obj;
    }

    /**
     * @return the m_isPrestart
     */
    public boolean isM_isPrestart() {
        return m_isPrestart;
    }

    /**
     * @param m_isPrestart the m_isPrestart to set
     */
    public Notify_PreStart setM_isPrestart(boolean m_isPrestart) {
        this.m_isPrestart = m_isPrestart;
        return this;
    }
}
