//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TALA_REPONSE_NAME.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.reponse.game.tala;


public class TALA_REPONSE_NAME {
	public static String FINISH = "game_finish_res";
        public static String GAME_RESULT = "game_result_res";
	public static String LOOSE_GAME = "loose_game_res";
	public static String SIT_ON_RES = "sit_on_res";
	public static String USER_SIT_ON_RES = "user_sit_on_res";
	public static String GET_PLAYER_CARD_RES = "get_player_card_req_res";
	public static String GET_NEXT_CARD_RES = "get_next_card_req_res";
	public static String END_GAME = "end_game_res";
	public static String SHOW_CARD = "show_card_res";
	public static String USER_ACTION = "user_action_res";
	public static String TURN = "turn_res";
	public static String START = "start_res";
	public static String PRE_START = "pre_start_res";
        public static String KICK_USER_RES = "kick_user_res";
        public static String MOVE_CARD_RES = "move_card_res";
        public static String DEN_BAI_RES = "den_bai_res";
        public static String USER_READY_RES = "user_ready_res";
}
