//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Login.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import com.smartfoxserver.bitswarm.sessions.Session;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.data.SFSObject;


public class Login extends SFSGameEvent {
    private Session m_session;
    private String m_name;
    private String m_password;
    private SFSObject m_inData;
    private SFSObject m_outData;
    
    @Override
    public String GetEventName() {
        return SFSEventType.USER_LOGIN.toString();
    }
    
    @Override
    public SFSGameEvent FromSFSEvent(ISFSEvent isfse) {
        setM_session((Session) isfse.getParameter(SFSEventParam.SESSION));
        setM_name((String) isfse.getParameter(SFSEventParam.LOGIN_NAME));
        setM_password((String) isfse.getParameter(SFSEventParam.LOGIN_PASSWORD));
        setM_inData((SFSObject) isfse.getParameter(SFSEventParam.LOGIN_IN_DATA));
        setM_outData((SFSObject) isfse.getParameter(SFSEventParam.LOGIN_OUT_DATA));
        return this;
    }

    /**
     * @return the m_session
     */
    public Session getM_session() {
        return m_session;
    }

    /**
     * @param m_session the m_session to set
     */
    public void setM_session(Session m_session) {
        this.m_session = m_session;
    }

    /**
     * @return the m_name
     */
    public String getM_name() {
        return m_name;
    }

    /**
     * @param m_name the m_name to set
     */
    public void setM_name(String m_name) {
        this.m_name = m_name;
    }

    /**
     * @return the m_password
     */
    public String getM_password() {
        return m_password;
    }

    /**
     * @param m_password the m_password to set
     */
    public void setM_password(String m_password) {
        this.m_password = m_password;
    }

    /**
     * @return the m_inData
     */
    public SFSObject getM_inData() {
        return m_inData;
    }

    /**
     * @param m_inData the m_inData to set
     */
    public void setM_inData(SFSObject m_inData) {
        this.m_inData = m_inData;
    }

    /**
     * @return the m_outData
     */
    public SFSObject getM_outData() {
        return m_outData;
    }

    /**
     * @param m_outData the m_outData to set
     */
    public void setM_outData(SFSObject m_outData) {
        this.m_outData = m_outData;
    }
}
