//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Logout.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.Room;
import com.smartfoxserver.v2.entities.User;
import java.util.List;
import java.util.Map;


public class Logout extends SFSGameEvent {
    private User m_user;
    private List<Room> m_joinedRooms;
    private Map<Room, Integer> m_playersIdByRoom;
    
    @Override
    public String GetEventName() {
        return SFSEventType.USER_LOGOUT.toString();
    }
    
    @Override
    public SFSGameEvent FromSFSEvent(ISFSEvent isfse) {
        setM_user((User) isfse.getParameter(SFSEventParam.USER));
        setM_joinedRooms((List<Room>) isfse.getParameter(SFSEventParam.JOINED_ROOMS));
        setM_playersIdByRoom((Map<Room, Integer>) isfse.getParameter(SFSEventParam.PLAYER_IDS_BY_ROOM));
        return this;
    }

    /**
     * @return the m_user
     */
    public User getM_user() {
        return m_user;
    }

    /**
     * @param m_user the m_user to set
     */
    public void setM_user(User m_user) {
        this.m_user = m_user;
    }

    /**
     * @return the m_joinedRooms
     */
    public List<Room> getM_joinedRooms() {
        return m_joinedRooms;
    }

    /**
     * @param m_joinedRooms the m_joinedRooms to set
     */
    public void setM_joinedRooms(List<Room> m_joinedRooms) {
        
        this.m_joinedRooms = m_joinedRooms;
    }

    /**
     * @return the m_playersIdByRoom
     */
    public Map<Room, Integer> getM_playersIdByRoom() {
        return m_playersIdByRoom;
    }

    /**
     * @param m_playersIdByRoom the m_playersIdByRoom to set
     */
    public void setM_playersIdByRoom(Map<Room, Integer> m_playersIdByRoom) {
        this.m_playersIdByRoom = m_playersIdByRoom;
        
    }

}
