//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PrivateMessage.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.Room;
import com.smartfoxserver.v2.entities.User;


public class PrivateMessage extends SFSGameEvent {
    private Room m_room;
    private User m_sender;
    private User m_recipient;
    private String m_message;
    
    @Override
    public String GetEventName() {
        return SFSEventType.PRIVATE_MESSAGE.toString();
    }
    
    @Override
    public SFSGameEvent FromSFSEvent(ISFSEvent isfse) {
        setM_room((Room) isfse.getParameter(SFSEventParam.ROOM));
        setM_sender((User) isfse.getParameter(SFSEventParam.USER));
        setM_recipient((User) isfse.getParameter(SFSEventParam.RECIPIENT));
        setM_message((String) isfse.getParameter(SFSEventParam.MESSAGE));
        return this;
    }

    /**
     * @return the m_room
     */
    public Room getM_room() {
        return m_room;
    }

    /**
     * @param m_room the m_room to set
     */
    public void setM_room(Room m_room) {
        this.m_room = m_room;
    }

    /**
     * @return the m_sender
     */
    public User getM_sender() {
        return m_sender;
    }

    /**
     * @param m_sender the m_sender to set
     */
    public void setM_sender(User m_sender) {
        this.m_sender = m_sender;
    }

    /**
     * @return the m_recipient
     */
    public User getM_recipient() {
        return m_recipient;
    }

    /**
     * @param m_recipient the m_recipient to set
     */
    public void setM_recipient(User m_recipient) {
        this.m_recipient = m_recipient;
    }

    /**
     * @return the m_message
     */
    public String getM_message() {
        return m_message;
    }

    /**
     * @param m_message the m_message to set
     */
    public void setM_message(String m_message) {
        this.m_message = m_message;
    }
}
