//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicMessage.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.Room;
import com.smartfoxserver.v2.entities.User;


public class PublicMessage extends SFSGameEvent {
    protected Room m_room;
    protected User m_sender;
    protected String m_message;
    
    @Override
    public String GetEventName() {
        return SFSEventType.PUBLIC_MESSAGE.toString();
    }
    
    @Override
    public SFSGameEvent FromSFSEvent(ISFSEvent isfse) {
        m_room = (Room) isfse.getParameter(SFSEventParam.ROOM);
        m_sender = (User) isfse.getParameter(SFSEventParam.USER);
        m_message = (String) isfse.getParameter(SFSEventParam.MESSAGE);
        return this;
    }
}
