//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RoomRemove.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.Room;


public class RoomRemove extends SFSGameEvent {
    private Room m_room;
    
    @Override
    public String GetEventName() {
        return SFSEventType.ROOM_REMOVED.toString();
    }
    
    @Override
    public SFSGameEvent FromSFSEvent(ISFSEvent isfse) {
        setM_room((Room) isfse.getParameter(SFSEventParam.ROOM));
        return this;
    }

    /**
     * @return the m_room
     */
    public Room getM_room() {
        return m_room;
    }

    /**
     * @param m_room the m_room to set
     */
    public void setM_room(Room m_room) {
        this.m_room = m_room;
    }
}
