//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RoomVariableUpdate.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.Room;
import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.variables.RoomVariable;
import java.util.List;


public class RoomVariableUpdate extends SFSGameEvent {
    private Room m_room;
    private User m_user;
    private List<RoomVariable> m_variables;
    
    @Override
    public String GetEventName() {
        return SFSEventType.ROOM_VARIABLES_UPDATE.toString();
    }
    
    @Override
    public SFSGameEvent FromSFSEvent(ISFSEvent isfse) {
        m_room = (Room) isfse.getParameter(SFSEventParam.ROOM);
        m_user = (User) isfse.getParameter(SFSEventParam.USER);
        m_variables = (List<RoomVariable>) isfse.getParameter(SFSEventParam.VARIABLES);
        return this;
    }

    /**
     * @return the m_room
     */
    public Room getM_room() {
        return m_room;
    }

    /**
     * @return the m_user
     */
    public User getM_user() {
        return m_user;
    }

    /**
     * @return the m_variables
     */
    public List<RoomVariable> getM_variables() {
        return m_variables;
    }
}
