//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Login.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import com.smartfoxserver.bitswarm.sessions.Session;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.data.SFSObject;


public class ServerReady extends SFSGameEvent {
    
    @Override
    public String GetEventName() {
        return SFSEventType.SERVER_READY.toString();
    }
    
    @Override
    public SFSGameEvent FromSFSEvent(ISFSEvent isfse) {
        return this;
    }
}
