//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SFSGameEvent.java
//  @ Date : 5/27/2012
//  @ Author : @ThongTrH
//
//



package casino.cardgame.message.event;

import casino.cardgame.message.IGameEvent;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.SFSEvent;


public abstract class SFSGameEvent implements IGameEvent {
    public abstract SFSGameEvent FromSFSEvent(ISFSEvent isfse);
}
