//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class GetDetailTourRes extends SFSGameReponse {

    private String _Name;
    private String _displayName;
    private int _Capacity;
    private int _numRegister;//number of user registed
    private double _betChip;
    private double _fee;
    private double _startingChip;
    private String _Status;
    private double _firstPrize;
    private double _secondPrize;
    private double _thirdPrize;
    private ArrayList<String> _listRegister;// list of user registed

    public GetDetailTourRes() {
        super(POKER_TOUR_RESPONSE_NAME.GET_DETAIL_TOUR_RES);
    }

     public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("name", _Name);
        obj.putUtfString("display_name", _displayName);
        obj.putInt("capacity", _Capacity);
        obj.putInt("register", _numRegister);
        obj.putDouble("bet_chip", _betChip);
        obj.putDouble("fee", _fee);
        obj.putDouble("starting_chip", _startingChip);
        obj.putUtfString("status", _Status);
        obj.putDouble("first_prize", _firstPrize);
        obj.putDouble("second_prize", _secondPrize);
        obj.putDouble("third_prize", _thirdPrize);
        
        SFSArray sfsRegister = new SFSArray();
        for(int i = 0; i< _listRegister.size(); i++){
            sfsRegister.addUtfString(_listRegister.get(i));
        }
        obj.putSFSArray("list_register", sfsRegister);
        
        return obj;
     }

    public GetDetailTourRes setCapacity(int Capacity) {
        this._Capacity = Capacity;
        return this;
    }

    public GetDetailTourRes setNumRegister(int Register) {
        this._numRegister = Register;
        return this;
    }

    public GetDetailTourRes setStatus(String Status) {
        this._Status = Status;
        return this;
    }

    public GetDetailTourRes setFirstPrize(double firstPrize) {
        this._firstPrize = firstPrize;
        return this;
    }

    public GetDetailTourRes setSecondPrize(double secondPrize) {
        this._secondPrize = secondPrize;
        return this;
    }

    public GetDetailTourRes setThirdPrize(double thirdPrize) {
        this._thirdPrize = thirdPrize;
        return this;
    }

    public GetDetailTourRes setListRegister(ArrayList<String> listRegister) {
        this._listRegister = listRegister;
        return this;
    }

    public GetDetailTourRes setName(String Name) {
        this._Name = Name;
        return this;
    }

    public GetDetailTourRes setBetChip(double betChip) {
        this._betChip = betChip;
        return this;
    }

    public GetDetailTourRes setFee(double fee) {
        this._fee = fee;
        return this;
    }

    public GetDetailTourRes setStartingChip(double startingChip) {
        this._startingChip = startingChip;
        return this;
    }

    public GetDetailTourRes setDisplayName(String displayName) {
        this._displayName = displayName;
        return this;
    }

}
