//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.entity.UserInfo;
import casino.cardgame.entity.game.TournamentEntity;
import casino.cardgame.message.reponse.game.poker.*;
import com.smartfoxserver.v2.entities.data.ISFSArray;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class GetListTournamentRes extends casino.cardgame.message.reponse.SFSGameReponse {

    private ISFSArray _arrTournaments;
    private boolean isRegistried;
    private String regisTourName;

    public GetListTournamentRes() {
        super(POKER_TOUR_RESPONSE_NAME.GET_LIST_TOUR_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        obj.putBool("is_registried", isRegistried);
        obj.putUtfString("tour_name", regisTourName);
        obj.putSFSArray("list_tournament", _arrTournaments);
        return obj;
    }

    public GetListTournamentRes setArrTournaments(ISFSArray arrTournaments) {
        this._arrTournaments = arrTournaments;
        return this;
    }
    
    public GetListTournamentRes setIsRegistried(boolean isRegistried) {
        this.isRegistried = isRegistried;
        return this;
    }

    public GetListTournamentRes setRegisTourName(String regisTourName) {
        this.regisTourName = regisTourName;
        return this;
    }
}
