//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class PenaltySitOutRes extends SFSGameReponse {

    private double _penaltyChip;//chip for user start game
    
    public PenaltySitOutRes() {
        super(POKER_TOUR_RESPONSE_NAME.PENALTY_SITOUT_RES);
    }

     public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putDouble("penalty_chip", _penaltyChip);
        return obj;
     }

    public void setPenaltyChip(double penaltyChip) {
        this._penaltyChip = penaltyChip;
    }

}
