//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TALA_REPONSE_NAME.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.game.tala.*;


public class POKER_TOUR_RESPONSE_NAME {
	public static String INVITE_TOUR_RES = "invite_tour_res";
	public static String BEGIN_TOUR_RES = "begin_tour_res";
	public static String END_TOUR_RES = "end_tour_res";
	public static String TRANSFER_ROOM_RES = "sit_on_res";
	public static String GET_LIST_TOUR_RES = "get_list_tour_res";
	public static String GET_DETAIL_TOUR_RES = "get_detail_tour_res";
	public static String REGISTRATION_RES = "registration_res";
	public static String REGISTRATION_ERROR_RES = "registration_error_res";
	public static String UNREGISTRATION_RES = "unregistration_res";
	public static String UNREGISTRATION_ERROR_RES = "unregistration_error_res";
	public static String PRESTART_TOUR_RES = "prestart_tour_res";
	public static String PENALTY_SITOUT_RES = "penalty_sitout_res";
	public static String USER_REWARD_RES = "user_reward_res";
	public static String TOURNAMENT_STATUS_CHANGE_RES = "tournament_status_change_res";
	public static String USER_COUNT_CHANGE_RES = "user_count_change_res";
        
        public static String TOUR_ADDED_RES = "tour_added_res";
        public static String TOUR_UPDATE_RES = "tour_update_res";
        public static String TOUR_DELETE_RES = "tour_delete_res";
        public static String UPDATE_TOUR_STATUS_RES = "update_tour_status_res";
}
