//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_PreStart.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : Broadcast ready time to all players in game board
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class PreStartTourRes extends casino.cardgame.message.reponse.SFSGameReponse {

    private String _tourName;
    private int _time;

    public PreStartTourRes() {
        super(POKER_TOUR_RESPONSE_NAME.PRESTART_TOUR_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("tour_name", _tourName);
        obj.putInt("time", _time);
        return obj;
    }

    public PreStartTourRes setTourName(String tourName) {
        this._tourName = tourName;
        return this;
    }

    public PreStartTourRes setTime(int time) {
        this._time = time;
        return this;
    }
}
