//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class RegistrationRes extends SFSGameReponse {

    private String _userName;
    private String _tourName;
    private double _fee;

    public RegistrationRes() {
        super(POKER_TOUR_RESPONSE_NAME.REGISTRATION_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", _userName);
        obj.putUtfString("tour_name", _tourName);
        obj.putDouble("fee", _fee);
        return obj;
    }

    public RegistrationRes setUserName(String userName) {
        this._userName = userName;
        return this;
    }

    public RegistrationRes setTourName(String tourName) {
        this._tourName = tourName;
        return this;
    }

    public RegistrationRes setFee(double fee) {
        this._fee = fee;
        return this;
    }
}
