//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class RegistrationErrorRes extends SFSGameReponse {

    private String _message;
    
    public RegistrationErrorRes() {
        super(POKER_TOUR_RESPONSE_NAME.REGISTRATION_ERROR_RES);
    }

     public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("message", _message);
        return obj;
     }

    public void setMessage(String message) {
        this._message = message;
    }

}
