//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class TourRemovedRes extends SFSGameReponse {

    private String _tourName;

    public TourRemovedRes() {
        super(POKER_TOUR_RESPONSE_NAME.TOUR_DELETE_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("name", _tourName);
        return obj;
    }

    public void setTourName(String tourName) {
        this._tourName = tourName;
    }
}
