//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class TournamentChangeStatusRes extends SFSGameReponse {

    private String _Name;
    private String _Status;

    public TournamentChangeStatusRes() {
        super(POKER_TOUR_RESPONSE_NAME.TOURNAMENT_STATUS_CHANGE_RES);
    }

     public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("name", _Name);
        obj.putUtfString("status", _Status);
        
        return obj;
     }


    public TournamentChangeStatusRes setStatus(String Status) {
        this._Status = Status;
        return this;
    }

    public TournamentChangeStatusRes setName(String Name) {
        this._Name = Name;
        return this;
    }

}
