//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.entity.game.TournamentEntity;
import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class TourUpdatedRes extends SFSGameReponse {

     private TournamentEntity _tourInfo;
    
    public TourUpdatedRes() {
        super(POKER_TOUR_RESPONSE_NAME.TOUR_UPDATE_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        obj.putUtfString("name", _tourInfo.getName());
        obj.putUtfString("display_name", _tourInfo.getDisplayName());
        obj.putDouble("fee", _tourInfo.getFee());
        obj.putDouble("starting_chip", _tourInfo.getStartingChip());
        obj.putInt("level_type", _tourInfo.getLevelType());
        obj.putInt("begin_level", _tourInfo.getBeginLevel());
        obj.putInt("end_level", _tourInfo.getEndLevel());
        obj.putInt("capacity", _tourInfo.getCapacity());
        obj.putDouble("first_prize", _tourInfo.getFirstPrize());
        obj.putDouble("second_prize", _tourInfo.getSecondPrize());
        obj.putDouble("third_prize", _tourInfo.getThirdPrize());
        
        return obj;
    }

    public void setTourInfo(TournamentEntity tourInfo) {
        this._tourInfo = tourInfo;
    }
}
