//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class UnregistrationRes extends SFSGameReponse {

    private String _userName;
    private String _tourName;
    private String _tourStatus;
    private double _fee;//return fee for user
    
    public UnregistrationRes() {
        super(POKER_TOUR_RESPONSE_NAME.UNREGISTRATION_RES);
    }

     public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", _userName);
        obj.putUtfString("tour_name", _tourName);
        obj.putUtfString("tour_status", _tourStatus);
        obj.putDouble("fee", _fee);
        return obj;
     }

    public UnregistrationRes setUserName(String userName) {
        this._userName = userName;
        return this;
    }

    public UnregistrationRes setTourName(String tourName) {
        this._tourName = tourName;
        return this;
    }

    public UnregistrationRes setTourStatus(String tourStatus) {
        this._tourStatus = tourStatus;
        return this;
    }

    public void setFee(double fee) {
        this._fee = fee;
    }

}
