//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class UpdateTourStatusRes extends SFSGameReponse {

    private String _name;
    private String _status;

    public UpdateTourStatusRes() {
        super(POKER_TOUR_RESPONSE_NAME.UPDATE_TOUR_STATUS_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("name", _name);
        obj.putUtfString("status", _status);
        return obj;
    }

    public void setName(String tourName) {
        this._name = tourName;
    }

    public void setStatus(String status) {
        this._status = status;
    }
}
