//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserBet.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class UserRewardRes extends SFSGameReponse {

    ///response for winner(1st, 2rd, 3nd) information about prize.
    
    
    private double _prize;
    private String _tourName;

    public UserRewardRes() {
        super(POKER_TOUR_RESPONSE_NAME.USER_REWARD_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putDouble("prize", _prize);
        obj.putUtfString("tour_name", _tourName);
        return obj;
    }

    public void setPrize(double prize) {
        this._prize = prize;
    }

    public void setTourName(String tourName) {
        this._tourName = tourName;
    }

}
