//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game.pokreTournament;

import casino.cardgame.entity.UserInfo;
import casino.cardgame.entity.game.TournamentEntity;
import casino.cardgame.message.reponse.game.poker.*;
import com.smartfoxserver.v2.entities.data.ISFSArray;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class UserCountChangeRes extends casino.cardgame.message.reponse.SFSGameReponse {

    private int _userCount;
    private String _tourNme;

    public UserCountChangeRes() {
        super(POKER_TOUR_RESPONSE_NAME.USER_COUNT_CHANGE_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        obj.putUtfString("tour_name", _tourNme);
        obj.putInt("user_count", _userCount);
        return obj;
    }

    public UserCountChangeRes setTourName(String tourName) {
        this._tourNme = tourName;
        return this;
    }

    public UserCountChangeRes setUserCount(int userCount) {
        this._userCount = userCount;
        return this;
    }
}
