//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IAdminController.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.controller.admin;

import casino.cardgame.message.event.SFSGameEvent;
import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.exceptions.SFSLoginException;

public interface IAdminController {
    public void HandleStartServerRequest(SFSGameRequest sfsreq);
    public void HandleStopServerRequest(SFSGameRequest sfsreq);
    public void HandleAdminMessageRequest(SFSGameRequest sfsreq);
    
    public void HandleAdminLogin(SFSGameEvent sfse) throws SFSLoginException ;
    public void HandleAdminLogout(SFSGameEvent igame) ;
}
