//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_FinishGame.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.poker;

import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_FinishGame extends SFSGameReponse {

    private ArrayList<String> listUser;
    private ArrayList<Double> listChip;
    private ArrayList<Integer> listPokerHandCard;
    private ArrayList<String> listPokerHand;
    private ArrayList<String> ListWinner;

    public Notify_FinishGame() {
        super(POKER_REPONSE_NAME.FINISH_GAME);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();

        //obj.putUtfString("poker_hand", listPokerHand);
        
        SFSArray sfsArrWinner = new SFSArray();
        for (int i = 0; i < ListWinner.size(); i++) {
            sfsArrWinner.addUtfString(ListWinner.get(i));
        }
        obj.putSFSArray("list_winner", sfsArrWinner);
        
        SFSArray sfsArrUser = new SFSArray();
        for (int i = 0; i < listUser.size(); i++) {
            sfsArrUser.addUtfString(listUser.get(i));
        }
        obj.putSFSArray("list_user", sfsArrUser);
        
        SFSArray sfsArrPokerHand = new SFSArray();
        for (int i = 0; i < listPokerHand.size(); i++) {
            sfsArrPokerHand.addUtfString(listPokerHand.get(i));
        }
        obj.putSFSArray("list_poker_Hand", sfsArrPokerHand);

        SFSArray sfsArrChip = new SFSArray();
        for (int i = 0; i < listChip.size(); i++) {
            sfsArrChip.addDouble(listChip.get(i));
        }
        obj.putSFSArray("list_chip", sfsArrChip);

        SFSArray sfsArrWinCard = new SFSArray();
        for (Integer card : listPokerHandCard) {
            sfsArrWinCard.addInt(card);
        }

        obj.putSFSArray("list_poker_hand_card", sfsArrWinCard);
        return obj;
    }

    public Notify_FinishGame setListUser(ArrayList<String> m_listUser) {
        this.listUser = m_listUser;
        return this;
    }


    public Notify_FinishGame setListChip(ArrayList<Double> m_listChip) {
        this.listChip = m_listChip;
        return this;
    }

    public Notify_FinishGame setListWinCard(ArrayList<Integer> listWinCard) {
        this.listPokerHandCard = listWinCard;
        return this;
    }

    public Notify_FinishGame setListPokerHand(ArrayList<String> pokerHand) {
        this.listPokerHand = pokerHand;
        return this;
    }

    public Notify_FinishGame setListWinner(ArrayList<String> ListWinner) {
        this.ListWinner = ListWinner;
        return this;
    }

}
