//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_ShowDown.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.poker;

import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_ShowDown extends SFSGameReponse {

    private ArrayList<String> listUser;
    private ArrayList<ArrayList<Integer>> listCard;
    private ArrayList<Integer> listComCard;
    private String currentGameTurn;

    public Notify_ShowDown() {
        super(POKER_REPONSE_NAME.SHOW_DOWN_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        obj.putUtfString("current_game_turn", currentGameTurn);
        
        SFSArray sfsArrUser = new SFSArray();
        for (int i = 0; i < listUser.size(); i++) {
            sfsArrUser.addUtfString(listUser.get(i));
        }
        obj.putSFSArray("list_user", sfsArrUser);

        SFSArray sfsArrCard = new SFSArray();
        for (int i = 0; i < listCard.size(); i++) {
            ArrayList<Integer> arrCardId = listCard.get(i);
            SFSArray arr = new SFSArray();

            for (Integer card : arrCardId) {
                arr.addInt(card);
            }

            sfsArrCard.addSFSArray(arr);
        }
        obj.putSFSArray("list_card", sfsArrCard);

        SFSArray sfsListComCard = new SFSArray();
        for (int i = 0; i < listComCard.size(); i++) {
            sfsListComCard.addInt(listComCard.get(i));
        }
        obj.putSFSArray("list_community_card", sfsListComCard);

        return obj;
    }

    public Notify_ShowDown setListUser(ArrayList<String> m_listUser) {
        this.listUser = m_listUser;
        return this;
    }

    public Notify_ShowDown setListCard(ArrayList<ArrayList<Integer>> m_listCard) {
        this.listCard = m_listCard;
        return this;
    }

    public Notify_ShowDown setListComCard(ArrayList<Integer> listComCard) {
        this.listComCard = listComCard;
        return this;
    }

    public void setCurrentGameTurn(String currentGameTurn) {
        this.currentGameTurn = currentGameTurn;
    }
}
