//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game.poker;

import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_Start extends casino.cardgame.message.reponse.SFSGameReponse {

    private String dealer;
    private String smallBlind;
    private String bigBlind;
    private String currentUser;
    private int userTime;//seconds
    private ArrayList<Integer> listCard;
    private ArrayList<String> listActiveUserName;
    private double betChipGame;
    private Integer levelTimeLife;
    private boolean isTurnNextLevel;

    public Notify_Start() {
        super(POKER_REPONSE_NAME.START);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();

        obj.putUtfString("dealer", dealer);
        obj.putUtfString("small_blind", smallBlind);
        obj.putUtfString("big_blind", bigBlind);
        obj.putUtfString("current_user", currentUser);
        obj.putInt("user_time", userTime);
        obj.putDouble("bet_chip_game", betChipGame);

        obj.putBool("is_turn_next_level", isTurnNextLevel);
        if (levelTimeLife != null) {
            obj.putInt("level_time_life", levelTimeLife);
        }

        SFSArray arrCard = new SFSArray();
        for (int i = 0; i < listCard.size(); i++) {
            arrCard.addInt(listCard.get(i));
        }
        obj.putSFSArray("list_card", arrCard);

        SFSArray arrActiveUserName = new SFSArray();
        for (int i = 0; i < listActiveUserName.size(); i++) {
            arrActiveUserName.addUtfString(listActiveUserName.get(i));
        }
        obj.putSFSArray("list_active_user_name", arrActiveUserName);

        return obj;
    }

    public Notify_Start setSmallBlind(String smallBlind) {
        this.smallBlind = smallBlind;
        return this;
    }

    public Notify_Start setBigBlind(String bigBlind) {
        this.bigBlind = bigBlind;
        return this;
    }

    public Notify_Start setCurrentUser(String currentUser) {
        this.currentUser = currentUser;
        return this;
    }

    public Notify_Start setUserTime(int userTime) {
        this.userTime = userTime;
        return this;
    }

    public Notify_Start setListCard(ArrayList<Integer> listCard) {
        this.listCard = listCard;
        return this;
    }

    public Notify_Start setBetChipGame(double betGameChip) {
        this.betChipGame = betGameChip;
        return this;
    }

    public Notify_Start setListActiveUserName(ArrayList<String> listActiveUserName) {
        this.listActiveUserName = listActiveUserName;
        return this;
    }

    public Notify_Start setDealer(String dealer) {
        this.dealer = dealer;
        return this;
    }

    public Notify_Start setLevelTimeLife(int levelTimeLife) {
        this.levelTimeLife = levelTimeLife;
        return this;
    }

    public boolean isIsTurnNextLevel() {
        return isTurnNextLevel;
    }

    public void setIsTurnNextLevel(boolean isTurnNextLevel) {
        this.isTurnNextLevel = isTurnNextLevel;
    }
}
