//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_userTurn.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.poker;

import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class Notify_GameTurn extends SFSGameReponse {

    private String currentUser;
    private ArrayList<Integer> listCommunityCard;
    private String currentGameTurn;
    private int time;
    
    public Notify_GameTurn() {
        super(POKER_REPONSE_NAME.GAME_TURN_RES);
    }
    
    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("current_user", currentUser);
        obj.putUtfString("current_game_turn", currentGameTurn);
        obj.putInt("time", time);
        
        SFSArray sfsCardIds = new SFSArray();
        for(Integer cardId: listCommunityCard){
            sfsCardIds.addInt(cardId);
        }   
        obj.putSFSArray("list_community_card", sfsCardIds);
        return obj;
     }

    public Notify_GameTurn setCurrentUser(String currentUser) {
        this.currentUser = currentUser;
        return this;
    }

    public Notify_GameTurn setListCommunityCard(ArrayList<Integer> listCommunityCard) {
        this.listCommunityCard = listCommunityCard;
        return this;
    }

    public Notify_GameTurn setTime(int time) {
        this.time = time;
        return this;
    }

    public Notify_GameTurn setCurrentGameTurn(String currentGameTurn) {
        this.currentGameTurn = currentGameTurn;
        return this;
    }
}
