//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_userTurn.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.poker;

import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_userTurn extends SFSGameReponse {

    private String userName;
    private double bettingChip;
    private int time;

    public Notify_userTurn() {
        super(POKER_REPONSE_NAME.USER_TURN_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", userName);
        obj.putDouble("betting_chip", bettingChip);
        obj.putInt("time", time);
        return obj;
    }

    public void setUserName(String currentUser) {
        this.userName = currentUser;
    }
    public void setTime(int time) {
        this.time = time;
    }

    public void setBettingChip(double bettingChip) {
        this.bettingChip = bettingChip;
    }
}
