//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserRaise.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.poker;

import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_UserRaise extends SFSGameReponse {

    private String userName;
    private Double chip;

    public Notify_UserRaise() {
        super(POKER_REPONSE_NAME.USER_RAISE_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", getUserName());
        obj.putDouble("chip", getChip());
        return obj;
    }

    public String getUserName() {
        return userName;
    }
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Double getChip() {
        return chip;
    }
    public void setChip(Double chip) {
        this.chip = chip;
    }
}
