//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Notify_UserCall.java
//  @ Date : 8/4/2012
//  @ Author : @khoa
//
//
package casino.cardgame.message.reponse.game.poker;

import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.data.SFSObject;

public class Notify_UserCall extends SFSGameReponse {

    private String userName;
    private Double chip;

    public Notify_UserCall() {
        super(POKER_REPONSE_NAME.USER_CALL_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_name", userName);
        obj.putDouble("chip", chip);
        return obj;
     }

    public void setUserName(String m_userName) {
        this.userName = m_userName;
    }
    public void setChip(Double chip) {
        this.chip = chip;
    }
}
