//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TALA_REPONSE_NAME.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.reponse.game.poker;

import casino.cardgame.message.reponse.game.tala.*;


public class POKER_REPONSE_NAME {
    	public static String LOAD_TABLE_INFO_RES = "load_table_info_res";
	public static String SIT_ON_RES = "sit_on_res";
	public static String STAND_UP_RES = "stand_up_res";
	public static String FINISH_GAME = "game_finish_res";
	public static String USER_SIT_ON_RES = "user_sit_on_res";
	public static String USER_SIT_OUT_RES = "user_sit_out_res";
	public static String START = "start_res";
	public static String PRE_START = "pre_start_res";
        public static String KICK_USER_RES = "kick_user_res";
        public static String USER_READY_RES = "user_ready_res";
        public static String SHOW_DOWN_RES = "show_down_res";
        public static String USER_BET_RES = "user_bet_res";
        public static String USER_CALL_RES = "user_call_res";
        public static String USER_CHECK_RES = "user_check_res";
        public static String USER_FOLD_RES = "user_fold_res";
        public static String USER_RAISE_RES = "user_raise_res";
        public static String USER_GOING_ALL_RES = "user_going_all_res";
        public static String GAME_TURN_RES = "game_turn_res";
        public static String USER_TURN_RES = "user_turn_res";
        public static String USER_BUY_IN_RES = "user_buy_in_res";
        public static String LEVEL_TURN_RES = "level_turn_res";
        public static String PAY_ANTE_RES = "pay_ante_res";
}
