//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : A_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//  @ Desc: Card Game Use for TaLa
//          id: 
//



package casino.cardgame.entity.game_entity.card;

import casino.cardgame.entity.game_entity.ICard;


public class A_Bich extends GameCard {

    public A_Bich(){
        super(11,"A_Bich",1);
    }
//    @Override
//    public CardCompare compare(ICard card) {
//        //dont use 
//        throw new UnsupportedOperationException("Not supported yet.");
//    }
}
