//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : A_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class A_Chuon extends GameCard {
    public A_Chuon(){
        super(12,"A_Chuon",1);
    }
    
}
