//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : A_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class A_Ro extends GameCard {
    public A_Ro(){
        super(13,"A_Ro",1);
    }
}
