//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Ba_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Ba_Bich extends GameCard {
    public Ba_Bich(){
        super(31,"Ba_Bich",3);
    }
}
