//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Ba_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Ba_Chuon extends GameCard {
    public Ba_Chuon(){
        super(32,"Ba_Chuon",3);
    }
}
