//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Ba_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Ba_Co extends GameCard {
    public Ba_Co(){
        super(34,"Ba_Co",3);
    }
}
