//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Ba_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Ba_Ro extends GameCard {
    public Ba_Ro(){
        super(33,"Ba_Ro",3);
    }
}
