//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bay_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bay_Bich extends GameCard {
    public Bay_Bich(){
        super(71,"Bay_Bich",7);
    }
}
