//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bay_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bay_Chuon extends GameCard {
    public Bay_Chuon(){
        super(72,"Bay_Chuon",7);
    }
}
