//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bay_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bay_Ro extends GameCard {
    public Bay_Ro(){
        super(73,"Bay_Ro",7);
    }
}
