//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bay_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bay_Co extends GameCard {
    public Bay_Co(){
        super(74,"Bay_Co",7);
    }
}
