//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bon_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bon_Ro extends GameCard {
    public Bon_Ro(){
        super(43,"Bon_Ro",4);
    }
}
