//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bon_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bon_Chuon extends GameCard {
    public Bon_Chuon(){
        super(42,"Bon_Chuon",4);
    }
}
