//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bon_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bon_Co extends GameCard {
    public Bon_Co(){
        super(44,"Bon_Co",4);
    }
}
