//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Bon_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Bon_Bich extends GameCard {
    public Bon_Bich(){
        super(41,"Bon_Bich",4);
    }
}
