//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Chin_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Chin_Bich extends GameCard {
    public Chin_Bich(){
        super(91,"Chin_Bich",9);
    }
}
