//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Chin_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Chin_Ro extends GameCard {
    public Chin_Ro(){
        super(93,"Chin_Ro",9);
    }
}
