//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Chin_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Chin_Co extends GameCard {
    public Chin_Co(){
        super(94,"Chin_Co",9);
    }
}
