//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Chin_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Chin_Chuon extends GameCard {
    public Chin_Chuon(){
        super(92,"Chin_Chuon",9);
    }
}
