//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GameCard.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;

import casino.cardgame.entity.game_entity.ICard;


public abstract class GameCard implements casino.cardgame.entity.game_entity.ICard {
    protected int m_id;
    protected String m_name;
    protected int m_value;
    public GameCard(int id,String name, int value){
        m_id = id;
        m_name = name;
        m_value = value;
    }
    @Override
    public int getCardId() {
        return m_id;
    }

    @Override
    public String getCardName() {
        return m_name;
    }

    @Override
    public int getCardValue() {
        return m_value;
    }
    //SangDN: Let child compare
    //Currently TaLa Card Don't use this function so not implement
    @Override
    public CardCompare compare(ICard card) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
