//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Hai_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Hai_Co extends GameCard {
    public Hai_Co(){
        super(24,"Hai_Co",2);
    }
}
