//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Hai_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Hai_Bich extends GameCard {
    public Hai_Bich(){
        super(21,"Hai_Bich",2);
    }
}
