//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Hai_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Hai_Ro extends GameCard {
    public Hai_Ro(){
        super(23,"Hai_Ro",2);
    }
}
