//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Hai_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Hai_Chuon extends GameCard {
    public Hai_Chuon(){
        super(22,"Hai_Chuon",2);
    }
}
