//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : J_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class J_Chuon extends GameCard {
    public J_Chuon(){
        super(112,"J_Chuon",11);
    }
}
