//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : J_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class J_Ro extends GameCard {
    public J_Ro(){
        super(113,"J_Ro",11);
    }
}
