//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : K_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class K_Chuon extends GameCard {
    public K_Chuon(){
        super(132,"K_Chuon",13);
    }
}
