//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Muoi_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Muoi_Co extends GameCard {
    public Muoi_Co(){
        super(104,"Muoi_Co",10);
    }
}
