//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Muoi_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Muoi_Bich extends GameCard {
    public Muoi_Bich(){
        super(101,"Muoi_Bich",10);
    }
}
