//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Muoi_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Muoi_Chuon extends GameCard {
    public Muoi_Chuon(){
        super(102,"Muoi_Chuon",10);
    }
}
