//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Muoi_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Muoi_Ro extends GameCard {
    public Muoi_Ro(){
        super(103,"Muoi_Ro",10);
    }
}
