//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Nam_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Nam_Bich extends GameCard {
    public Nam_Bich(){
        super(51,"Nam_Bich",5);
    }
}
