//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Nam_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Nam_Chuon extends GameCard {
    public Nam_Chuon(){
        super(52,"Nam_Chuon",5);
    }
}
