//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Nam_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Nam_Co extends GameCard {
    public Nam_Co(){
        super(54,"Nam_Co",5);
    }
}
