//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Nam_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Nam_Ro extends GameCard {
    public Nam_Ro(){
        super(53,"Nam_Ro",5);
    }
}

