//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Q_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Q_Bich extends GameCard {
    public Q_Bich(){
        super(121,"Q_Bich",12);
    }
}
