//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Q_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Q_Chuon extends GameCard {
    public Q_Chuon(){
        super(122,"Q_Chuon",12);
    }
}
