//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Q_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Q_Ro extends GameCard {
    public Q_Ro(){
        super(123,"Q_Ro",12);
    }
}
