//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Sau_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Sau_Bich extends GameCard {
    public Sau_Bich(){
        super(61,"Sau_Bich",6);
    }
}
