//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Sau_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Sau_Chuon extends GameCard {
    public Sau_Chuon(){
        super(62,"Sau_Chuon",6);
    }
}

