//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Sau_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Sau_Ro extends GameCard {
    public Sau_Ro(){
        super(63,"Sau_Ro",6);
    }
}
