//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Sau_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Sau_Co extends GameCard {
    public Sau_Co(){
        super(64,"Sau_Co",6);
    }
}
