//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Tam_Chuon.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Tam_Chuon extends GameCard {
    public Tam_Chuon(){
        super(82,"Tam_Chuon",8);
    }
}
