//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Tam_Ro.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Tam_Ro extends GameCard {
    public Tam_Ro(){
        super(83,"Tam_Ro",8);
    }
}
