//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Tam_Bich.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Tam_Bich extends GameCard {
    public Tam_Bich(){
        super(81,"Tam_Bich",8);
    }
}
