//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Tam_Co.java
//  @ Date : 6/18/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game_entity.card;


public class Tam_Co extends GameCard {
    public Tam_Co(){
        super(84,"Tam_Co",8);
    }
}
