//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : UserInfo.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game;

import com.smartfoxserver.v2.entities.variables.SFSUserVariable;
import com.smartfoxserver.v2.entities.variables.UserVariable;
import hirondelle.date4j.DateTime;
import java.util.ArrayList;
import java.util.List;


public class LevelCollectionEntity {
    private int _id;
    private String _description;

    public LevelCollectionEntity(int id, String description){
                    _id = id;
                    _description = description;
    }

    public int getId() {
        return _id;
    }

    public void setId(int id) {
        this._id = id;
    }

    public String getDescription() {
        return _description;
    }

    public void setDescription(String description) {
        this._description = description;
    }

}
