//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TableHistory.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game;

import casino.cardgame.entity.TableResult;
import hirondelle.date4j.DateTime;
import java.util.Date;
import java.util.List;

public abstract class TableHistory {
	private int id;
	private Date StartedTime;
	private Date EndedTime;
	private List<String> ListPlayer;
	private List<String> ListSpectator;
	private List<TableResult> ListTableResult;
	
        public void addPlayedUser(String strUserName) {
	
	}
	
	public void addJoinedUser(String strUserName) {
	
	}
	
	public List<String> GetAllJoinedUser() {
            return null;
	}
	
	public void ITableHistory(int id, DateTime start, DateTime end, List<String> listPlayedUser
                , List<String> listJoinedUser, List<Integer> listTableResult) {
	
	}

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the StartedTime
     */
    public Date getStartedTime() {
        return StartedTime;
    }

    /**
     * @param StartedTime the StartedTime to set
     */
    public void setStartedTime(Date StartedTime) {
        this.StartedTime = StartedTime;
    }

    /**
     * @return the EndedTime
     */
    public Date getEndedTime() {
        return EndedTime;
    }

    /**
     * @param EndedTime the EndedTime to set
     */
    public void setEndedTime(Date EndedTime) {
        this.EndedTime = EndedTime;
    }

    /**
     * @return the ListPlayer
     */
    public List<String> getListPlayer() {
        return ListPlayer;
    }

    /**
     * @param ListPlayer the ListPlayer to set
     */
    public void setListPlayer(List<String> ListPlayer) {
        this.ListPlayer = ListPlayer;
    }

    /**
     * @return the ListSpectator
     */
    public List<String> getListSpectator() {
        return ListSpectator;
    }

    /**
     * @param ListSpectator the ListSpectator to set
     */
    public void setListSpectator(List<String> ListSpectator) {
        this.ListSpectator = ListSpectator;
    }

    /**
     * @return the ListTableResult
     */
    public List<TableResult> getListTableResult() {
        return ListTableResult;
    }

    /**
     * @param ListTableResult the ListTableResult to set
     */
    public void setListTableResult(List<TableResult> ListTableResult) {
        this.ListTableResult = ListTableResult;
    }
}
