//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TLMNTableHistory.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.entity.game;


public class TLMNTableHistory extends casino.cardgame.entity.game.TableHistory {
}
