//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.admin;

import casino.cardgame.entity.UserInfo;
import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class AddUserChipResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private boolean _result;
    private String _message; 
    
    public AddUserChipResponse() {
        super(ADMIN_RESPONSE_TYPE.ADD_CHIP_FOR_USER_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("message", _message);
        obj.putBool("result", _result);
        return obj;
    }

    public void setMessage(String message) {
        this._message = message;
    }

    public void setResult(boolean result) {
        this._result = result;
    }

}
