//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ADMIN_RESPONSE_TYPE.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//

package casino.cardgame.message.reponse.admin;


public class ADMIN_RESPONSE_TYPE {

    public static String START_SERVER_RESPONSE = "start_server_res";
    public static String STOP_SERVER_RESPONSE = "stop_server_res";
    
    public static String GET_LIST_USER_RES = "get_list_user_res";
    public static String GET_LIST_ROOM_RES = "get_list_room_res";
    public static String GET_LIST_TOURNAMENT_RES = "get_list_tournament_res";
    public static String GET_LIST_LEVEL_RES = "get_list_level_res";
    public static String GET_LEVEL_COLLECTION_RES = "get_level_collection_res";
    
    public static String CREATE_RES = "create_res";
    public static String UPDATE_RES = "update_res";
    public static String DELETE_RES = "delete_res";
    
    public static String CREATE_ERROR_RES = "create_error_res";
    public static String UPDATE_ERROR_RES = "update_error_res";
    public static String DELETE_ERROR_RES = "delete_error_res";
    
    public static String ADD_CHIP_FOR_USER_RES = "add_chip_for_user_res";
    
    public static String GET_TRANSACTION_RES = "get_transaction_res";
}
