//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.admin;

import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class DeleteErrorResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private String _message;
    private String _objDeleted;

    public DeleteErrorResponse() {
        super(ADMIN_RESPONSE_TYPE.DELETE_ERROR_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("message", _message);
        obj.putUtfString("object_deleted", _objDeleted);
        return obj;
    }

    public void setMessage(String message) {
        this._message = message;
    }
    
    public void setObjDeleted(String objCreated) {
        this._objDeleted = objCreated;
    }
}
