//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.admin;

import casino.cardgame.entity.RoomInfo;
import casino.cardgame.entity.UserInfo;
import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.data.ISFSArray;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class GetListRoomResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private ArrayList<RoomInfo> _listRoom; 
    private ISFSArray _arrRooms;
    
    public GetListRoomResponse() {
        super(ADMIN_RESPONSE_TYPE.GET_LIST_ROOM_RES);
    }

//    public SFSObject ToSFSObject() {
//        SFSObject obj = new SFSObject();
//        
//        SFSArray sfsArrRooms = new SFSArray();
//        for(int i = 0; i< _listRoom.size(); i++){
//            SFSObject sfsRoom = new SFSObject();
//            RoomInfo room = _listRoom.get(i);
//            
//            sfsRoom.putUtfString("name", room.getRoomName());
//            sfsRoom.putUtfString("display_name", room.getDisplayName());
//            sfsRoom.putUtfString("password", room.getPassword());
//            sfsRoom.putDouble("bet_chip", room.getBetChip());
//            sfsRoom.putDouble("small_blind", room.getSmallBlind());
//            sfsRoom.putDouble("big_blind", room.getBigBlind());
//            sfsRoom.putDouble("max_user", room.getMaxUsers());
//            sfsRoom.putDouble("min_chip", room.getMinChip());
//            sfsRoom.putDouble("max_chip", room.getMaxChip());
//            sfsRoom.putUtfString("create_by", room.getCreateBy());
//            sfsRoom.putUtfString("status", room.getStatus());
//            
//            sfsArrRooms.addSFSObject(sfsRoom);
//        }
//        
//        obj.putSFSArray("list_room", sfsArrRooms);
//        return obj;
//    }
    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        obj.putSFSArray("list_room", _arrRooms);
        return obj;
    }

    public void setListRoom(ArrayList<RoomInfo> listRoom) {
        this._listRoom = listRoom;
    }

    public void setArrRooms(ISFSArray arrRooms) {
        this._arrRooms = arrRooms;
    }

}
