//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.admin;

import casino.cardgame.entity.UserInfo;
import casino.cardgame.entity.game.TournamentEntity;
import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.data.ISFSArray;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class GetListTournamentResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private ArrayList<TournamentEntity> _listTour; 
    private ISFSArray _arrTournaments;
    
    public GetListTournamentResponse() {
        super(ADMIN_RESPONSE_TYPE.GET_LIST_TOURNAMENT_RES);
    }

//    public SFSObject ToSFSObject() {
//        SFSObject obj = new SFSObject();
//        
//        SFSArray sfsArrTours = new SFSArray();
//        for(int i = 0; i< _listTour.size(); i++){
//            SFSObject sfsTour = new SFSObject();
//            TournamentEntity tour = _listTour.get(i);
//            sfsTour.putUtfString("name", tour.getName());
//            sfsTour.putUtfString("display_name", tour.getDisplayName());
//            sfsTour.putDouble("fee", tour.getFee());
//            sfsTour.putDouble("starting_chip", tour.getStartingChip());
//            sfsTour.putDouble("bet_chip", tour.getBetChip());
//            sfsTour.putDouble("small_blind", tour.getSmallBlind());
//            sfsTour.putDouble("big_blind", tour.getBigBlind());
//            sfsTour.putInt("capacity", tour.getCapacity());
//            sfsTour.putDouble("frist_prize", tour.getFirstPrize());
//            sfsTour.putDouble("second_prize", tour.getSecondPrize());
//            sfsTour.putDouble("third_prize", tour.getThirdPrize());
//            
//            sfsArrTours.addSFSObject(sfsTour);
//        }
//        
//        obj.putSFSArray("list_tournament", sfsArrTours);
//        return obj;
//    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        obj.putSFSArray("list_tournament", _arrTournaments);
        return obj;
    }
    
    public void setListTour(ArrayList<TournamentEntity> listTour) {
        this._listTour = listTour;
    }

    public void setArrTournaments(ISFSArray arrTournaments) {
        this._arrTournaments = arrTournaments;
    }

}
