//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.admin;

import casino.cardgame.entity.RoomInfo;
import casino.cardgame.entity.UserInfo;
import casino.cardgame.message.reponse.game.poker.*;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.data.ISFSArray;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;

public class GetTransactionResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private ISFSArray _arrTrasactions;
    
    public GetTransactionResponse() {
        super(ADMIN_RESPONSE_TYPE.GET_TRANSACTION_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        obj.putSFSArray("list_transaction", _arrTrasactions);
        return obj;
    }

    public void setArrTrasactions(ISFSArray arrTrasactions) {
        this._arrTrasactions = arrTrasactions;
    }


}
