//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : StartServerResponse.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//
package casino.cardgame.message.reponse.admin;

import casino.cardgame.message.reponse.SFSGameReponse;
import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.ISFSObject;

public class StartServerResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    public StartServerResponse() {
        super(ADMIN_RESPONSE_TYPE.START_SERVER_RESPONSE);
    }
}
