//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IUserController.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.controller.user;

import casino.cardgame.controller.server.IServerController;
import casino.cardgame.message.event.SFSGameEvent;
import com.smartfoxserver.v2.exceptions.SFSLoginException;


public interface IUserController {
    
    public void HandleUserLogin(SFSGameEvent sfse) throws SFSLoginException ;
    public void HandleUserLogout(SFSGameEvent igame) ;
    public void HandleUserJoinZone(SFSGameEvent joinZoneEvt);
}
