//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IMemoryCached.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.utils.data;

import casino.cardgame.entity.LeaderBoardInfo;
import casino.cardgame.entity.LoginHistory;
import casino.cardgame.entity.RoomHistory;
import casino.cardgame.entity.ServerStateHistory;
import casino.cardgame.entity.TableResult;
import casino.cardgame.entity.TopWinnerInfo;
import casino.cardgame.entity.TransactionInfo;
import casino.cardgame.entity.UserInfo;
import casino.cardgame.entity.game.TableHistory;
import hirondelle.date4j.DateTime;
import java.util.List;


public interface IMemoryCached {
        public void cacheUserInfo(UserInfo info);        
        public void cacheUserPass(String strUserName, String pass);
        public void cacheTableResult(TableResult result);
        public void cacheTransactionInfo(TransactionInfo trans);
        public void cacheTableHistory(TableHistory tblHistory);
        public void cacheLoginHistory(LoginHistory loginHistory);
        public void cacheRoomHistory(RoomHistory room);
        public void cacheLeaderBoardInfo(List<LeaderBoardInfo> list);
        public void cacheTopWinnerInfo(List<TopWinnerInfo> list);
        public casino.cardgame.entity.UserInfo GetUserInfo(String strUserName) ;
	
	public String GetUserPassword(String strUserName) ;
	
	public casino.cardgame.entity.TableResult GetTableResult(String tblId) ;
	
	public casino.cardgame.entity.TransactionInfo GetTransactionInfo(String strOwnerName) ;
	
	public List<TransactionInfo> GetTransactionHistory(String strOwnerName, DateTime fromDate, DateTime toDate) ;
	
	public List<TransactionInfo> GetTransactionHistory(String strOwnerName, int fromIndex, int numRecord) ;
	
	public casino.cardgame.entity.game.TableHistory GetTableHistory(String tableID) ;
	
	public List<LoginHistory> GetLoginHistory(String strUserName, DateTime fromDate, DateTime toDate) ;
	
	public List<LoginHistory> GetLoginHistory(String strUserName, int fromIndex, int numRecord) ;
	
	public List<RoomHistory> GetCreatedRoomHistory(DateTime fromDate, DateTime toDate) ;
	
	public List<RoomHistory> GetCreatedRoomHistory(int fromIndex, int numRecord) ;
	
	public List<ServerStateHistory> GetServerStateHistory(DateTime fromDate, DateTime toDate) ;
	
	public List<ServerStateHistory> GetServerStateHistory(int fromIndex, int numRecord) ;
	
	public List<LeaderBoardInfo> GetLeaderBoard();
	
	public List<TopWinnerInfo> GetTopWiner();
        
}
