//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IGameEvent.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message;


public interface IGameEvent {
	public String GetEventName();
}
