//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IGameRequest.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message;


public interface IGameRequest {
	public String GetRequestName();
        
}
