//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : MessageName.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message;


public class MessageName {
	public String MSG_LOGIN_FAIL = " MSG_LOGIN_FAIL";
	public String MSG_LOGIN_SUCCESS = "MSG_LOGIN_SUCCESS";
	public String MSG_ROOM_VAR_UPDATED = "MSG_ROOM_VARIABLE_UPDATED";
	public String MSG_CONNECTION_SUCCESS = "MSG_CONNECTIO_SUCCESS";
	public String MSG_CONNECTION_LOST = "MSG_CONNECTION_LOST";
	public String MSG_ROOM_REMOVED = "MSG_ROOM_REMOVED";
	public String MSG_LOGOUT_FAIL = "MSG_LOGOUT_FAIL";
	public String MSG_LOGOUT_SUCCESS = "MSG_LOGOUT_SUCCESS";
	public String MSG_ROOM_CREATOR_ERROR = "MSG_ROOM_CREATOR_ERROR";
	public String MSG_GAME_REPORTED = "MSG_GAME_REPORTED";
	public String MSG_ROOM_ADDED = "MSG_ROOM_ADDED";
	public String MSG_BANNED = "MSG_BANNED";
	public String MSG_INVITATION_REPLY = "MSG_INVITATION_REPLY";
	public String MSG_USER_EXIT_ROOM = "MSG_USER_EXIT_ROOM";
	public String MSG_USER_ENTER_ROOM = "MSG_USER_ENTER_ROOM";
	public String MSG_PRIVATE_MESSAGE = "MSG_PRIVATE_MESSAGE";
	public String MSG_PUBLIC_MESSAGE = "MSG_PUBLIC_MESSAGE";
	public String MSG_USER_COUNT_CHANGE = "MSG_USER_COUNT_CHANGE";
	public String MSG_PLAYER2SPEC = "MSG_PLAYER_TO_SPECTATOR";
	public String MSG_SPEC2PLAYER = "MSG_SPECTATOR_TO_PLAYER";
	public String MSG_REGISTER = "MSG_REGISTER";
	public String MSG_TRANSACTION_INFO = "MSG_TRANSACTION_INFO";
	public String MSG_LOGIN_HISTORY = "MSG_LOGIN_HISTORY";
	public String MSG_USER_INFO = "MSG_USER_INFO";
}
