//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : MessageType.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message;


public class MessageType{
	public String MSG_4_USER = "MSG_4_USER";
	public String MSG_4_MANAGER = "MSG_4_MANAGER";
	public String MSG_4_GAME = "MSG_4_GAME";
	public String MSG_4_UNKNOW = "MSG_4_UNKNOW";
}
