//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : BannedRequest.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.request;

import com.smartfoxserver.v2.entities.data.ISFSObject;
import com.smartfoxserver.v2.entities.data.ISFSObject;



public class BannedRequest extends SFSGameRequest {

    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        
        return this;
    }

    @Override
    public String GetRequestName() {
        return GAME_REQUEST_NAME.BANNED_REQ;
    }
}
