//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetTransactionInfoRequest.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.request;

import com.smartfoxserver.v2.entities.data.ISFSObject;


public class GetTransactionInfoRequest extends SFSGameRequest {
    public String USERNAME;

    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        return this;
    }

    @Override
    public String GetRequestName() {
        return GAME_REQUEST_NAME.GET_TRANS_BY_USER_REQ;
    }
}
