//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : SFSGameRequest.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.request;

import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.logging.Level;
import java.util.logging.Logger;


public abstract class SFSGameRequest implements casino.cardgame.message.IGameRequest {
    private User m_user;
    public abstract SFSGameRequest FromSFSObject(ISFSObject isfso) ;

    /**
     * @return the m_user
     */
    public User getM_user() {
        return m_user;
    }

    /**
     * @param m_user the m_user to set
     */
    //khoatd
    public void setM_user(User m_user) {
        this.m_user = m_user;
    }
    
}
