//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : PUBLIC_MESSAGE.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package sfs2x.extension.realpokerserver.src.sfsHandler;

import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.extensions.BaseServerEventHandler;


public class PUBLIC_MESSAGE  extends BaseServerEventHandler{
        @Override
	public void handleServerEvent(ISFSEvent isfse) {
	
	}
}
