//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ROOM_VARIABLES_UPDATE.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package sfs2x.extension.realpokerserver.src.sfsHandler;

import casino.cardgame.message.event.RoomVariableUpdate;
import casino.cardgame.utils.Logger;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.extensions.BaseServerEventHandler;


public class ROOM_VARIABLES_UPDATE extends BaseServerEventHandler{
        @Override
	public void handleServerEvent(ISFSEvent isfse) {
            try{
                Logger.trace("Enter ROOM_VSARIABLES_UPDATE Event");
                RoomVariableUpdate evt = (RoomVariableUpdate) new RoomVariableUpdate().FromSFSEvent(isfse);
                
            }catch(Exception ex){
                Logger.error(this.getClass(), ex);
            }
	}
}
