//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ROOM_REMOVED.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package sfs2x.extension.realpokerserver.src.sfsHandler;

import casino.cardgame.controller.game.table.TaLaController;
import casino.cardgame.message.event.RoomRemove;
import casino.cardgame.utils.GlobalValue;
import casino.cardgame.utils.Logger;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.extensions.BaseServerEventHandler;


public class ROOM_REMOVED extends BaseServerEventHandler{
        @Override
	public void handleServerEvent(ISFSEvent isfse) {
            try{
                Logger.trace("Enter Room_Removed Event");
                GlobalValue.serverHandler.HandleRoomRemoved(isfse);
            }catch(Exception ex){
                Logger.error(this.getClass(), ex);
            }
	}
}
