//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : SERVER_READY.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package sfs2x.extension.realpokerserver.src.sfsHandler;

import casino.cardgame.utils.GlobalValue;
import casino.cardgame.utils.Logger;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.extensions.BaseServerEventHandler;


public class SERVER_READY  extends BaseServerEventHandler{
        @Override
	public void handleServerEvent(ISFSEvent isfse) {
            try{
                Logger.trace("Server Ready Event");
                GlobalValue.serverHandler.HandleServerReady(isfse);
            }catch(Exception ex){
                Logger.error(this.getClass(), ex);
            }
	}
}
