//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : USER_LOGIN.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//
package sfs2x.extension.realpokerserver.src.sfsHandler;

import casino.cardgame.game_enum.RoomVariableDetail;
import casino.cardgame.utils.GlobalValue;
import casino.cardgame.utils.Logger;
import com.smartfoxserver.v2.api.CreateRoomSettings;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.entities.Zone;
import com.smartfoxserver.v2.entities.variables.RoomVariable;
import com.smartfoxserver.v2.entities.variables.SFSRoomVariable;
import com.smartfoxserver.v2.exceptions.SFSCreateRoomException;
import com.smartfoxserver.v2.exceptions.SFSLoginException;
import com.smartfoxserver.v2.extensions.BaseServerEventHandler;
import com.smartfoxserver.v2.game.CreateSFSGameSettings;
import java.util.ArrayList;

public class USER_LOGIN extends BaseServerEventHandler {

    @Override
    public void handleServerEvent(ISFSEvent isfse) throws SFSLoginException {
        Logger.trace("Enter USER_LOGIN Event");
        GlobalValue.serverHandler.HandleUserLogin(isfse);

    }

}
