//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : USER_JOIN_ROOM.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//
package sfs2x.extension.realpokerserver.src.sfsHandler;

import casino.cardgame.controller.game.GameController;
import casino.cardgame.controller.game.table.TaLaController;
import casino.cardgame.entity.game_entity.Desk;
import casino.cardgame.entity.game_entity.tala.TaLaTableInfo;
import casino.cardgame.message.event.UserJoinRoom;
import casino.cardgame.utils.GlobalValue;
import casino.cardgame.utils.Logger;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.core.ISFSEventParam;
import com.smartfoxserver.v2.core.SFSEventParam;
import com.smartfoxserver.v2.core.SFSEventType;
import com.smartfoxserver.v2.entities.Room;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import com.smartfoxserver.v2.entities.variables.RoomVariable;
import com.smartfoxserver.v2.extensions.BaseServerEventHandler;
import java.util.List;

public class USER_JOIN_ROOM extends BaseServerEventHandler {

    @Override
    public void handleServerEvent(ISFSEvent isfse) {
        try {
            Logger.trace("Enter USER_JOIN_ROOM Event");
            GlobalValue.serverHandler.HandleUserJoinRoom(isfse);

        } catch (Exception ex) {
            Logger.error(this.getClass(), ex);
        }
    }
}
