//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : USER_LOGOUT.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//
package sfs2x.extension.realpokerserver.src.sfsHandler;

import casino.cardgame.utils.GlobalValue;
import casino.cardgame.utils.Logger;
import com.smartfoxserver.v2.core.ISFSEvent;
import com.smartfoxserver.v2.extensions.BaseServerEventHandler;

public class USER_LOGOUT extends BaseServerEventHandler {

    @Override
    public void handleServerEvent(ISFSEvent isfse) {
        try {
            Logger.trace("Enter USER_LOGOUT Event");
            GlobalValue.serverHandler.HandleUserLogout(isfse);
        } catch (Exception ex) {
            casino.cardgame.utils.Logger.error(ex);
        }
    }
}
