//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : ITableController.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.controller.game.table;

import casino.cardgame.message.IGameRequest;
import casino.cardgame.message.event.SFSGameEvent;
import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.User;

public interface ITableController {
    
    public void HandleGameMessage(User sender, IGameRequest request);
    public void HandleUserDisconnect(SFSGameEvent evt) ;
    public void HandleUserLogout(SFSGameEvent evt) ;
    public void HandleUserJoinRoom(SFSGameEvent evt) ;
    public void HandleUserLeaveRoom(SFSGameEvent evt);
    public void HandleRoomRemove(SFSGameEvent evt);
    public void Start();
            
}
