//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TableController.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.controller.game.table;

import casino.cardgame.entity.game_entity.Desk;
import casino.cardgame.message.IGameRequest;
import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.game.SFSGame;
import java.util.HashMap;
import java.util.List;


public abstract class TableController implements ITableController {
	
}
