//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.game.poker;

import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Timer;


public class BetRequest extends casino.cardgame.message.request.SFSGameRequest {
    
    private double betChip;
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        betChip = isfso.getDouble("bet_chip");
        return this;
    }

    @Override
    public String GetRequestName() {
        return POKER_REQUEST_NAME.BET_REQ;
    }

    public double getBetChip() {
        return betChip;
    }

    
}
