//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TALA_REQUEST_NAME.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//



package casino.cardgame.message.request.game.poker;

import casino.cardgame.message.request.game.tala.*;


public class POKER_REQUEST_NAME {
	public static String BUY_IN_REQ = "buy_in_req";
	public static String SIT_ON_REQ = "sit_on_req";
	public static String SIT_OUT_REQ = "sit_out_req";
	public static String STAND_UP_REQ = "stand_up_req";
	public static String BET_REQ = "bet_req";
	public static String CALL_REQ = "call_req";
	public static String RAISE_REQ = "raise_req";
	public static String CHECK_REQ = "check_req";
	public static String FOLD_REQ = "fold_req";
	public static String GOING_ALL_REQ = "going_all_req";
        public static String CONFIRM_READY_GAME = "confirm_ready_game_req";
}
