//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.game.poker;

import casino.cardgame.message.request.GAME_REQUEST_NAME;
import casino.cardgame.message.request.SFSGameRequest;
import casino.cardgame.message.request.game.poker.POKER_REQUEST_NAME;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Timer;


public class StandUpRequest extends casino.cardgame.message.request.SFSGameRequest {
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        return this;
    }

    @Override
    public String GetRequestName() {
        return POKER_REQUEST_NAME.STAND_UP_REQ;
    }

}
