//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.game.pokerTournament;

import casino.cardgame.message.request.game.poker.*;
import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Timer;


public class CreateTournamentRequest extends casino.cardgame.message.request.SFSGameRequest {
    
    //tournament Name
    private String _tournamentName;
    //prize of 1st, 2nd, 3rd player.
    private double _firstPrize;
    private double _secondPrize;
    private double _thirdPrize;
    
    private double _betChip;
    //numbers of players join in tournament
    private int _playerCapacity;
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        _tournamentName = isfso.getUtfString("tournament_name");
        _firstPrize = isfso.getDouble("first_prize");
        _secondPrize = isfso.getDouble("first_prize");
        _thirdPrize = isfso.getDouble("first_prize");
        _playerCapacity = isfso.getInt("player_capacity");
        _betChip = isfso.getDouble("bet_chip");
        return this;
    }

    @Override
    public String GetRequestName() {
        return POKER_TOUR_REQUEST_NAME.CREATE_TOUR;
    }

    public double getBetChip() {
        return _betChip;
    }

    public String getTournamentName() {
        return _tournamentName;
    }

    public double getFirstPrize() {
        return _firstPrize;
    }

    public double getSecondPrize() {
        return _secondPrize;
    }

    public double getThirdPrize() {
        return _thirdPrize;
    }

    public int getPlayerCapacity() {
        return _playerCapacity;
    }

    
}
