//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TALA_REQUEST_NAME.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//



package casino.cardgame.message.request.game.pokerTournament;

import casino.cardgame.message.request.game.poker.*;
import casino.cardgame.message.request.game.tala.*;


public class POKER_TOUR_REQUEST_NAME {
	public static String CREATE_TOUR = "create_tour";
	public static String STOP_TOUR = "stop_tour";
	public static String PENDING_TOUR = "pending_tour";
	public static String DESTROY_TOUR = "destroy_tour";
	public static String GET_LIST_TOUR = "get_list_tour";
	public static String GET_DETAIL_TOUR = "get_detail_tour";
	public static String REGISTRY_TOUR = "registry_tour";
	public static String UNREGISTRY_TOUR = "unregistry_tour";
	public static String REPLY_INVITE_TOUR = "reply_invite_tour";
}
