//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.game.pokerTournament;

import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;


public class ReplyInviteTourRequest extends casino.cardgame.message.request.SFSGameRequest {
    
    //tournament Name
    private String _tourName;
    private boolean _isAccept;
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        _tourName = isfso.getUtfString("tour_name");
        _isAccept = isfso.getBool("is_accept");
        return this;
    }

    @Override
    public String GetRequestName() {
        return POKER_TOUR_REQUEST_NAME.REPLY_INVITE_TOUR;
    }

    public String getTourName() {
        return _tourName;
    }

    public boolean isAccept() {
        return _isAccept;
    }


}
