//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player
package casino.cardgame.message.request.admin;

import casino.cardgame.entity.RoomInfo;
import casino.cardgame.entity.TransactionInfo;
import casino.cardgame.entity.UserInfo;
import casino.cardgame.game_enum.RoomStatus;
import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.Timer;

public class AddChipForUserRequest extends SFSGameRequest {

    private TransactionInfo _transaction;

    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        String userName = isfso.getUtfString("user_name");
        String type = isfso.getUtfString("type");
        double amount = isfso.getDouble("amount");

        _transaction = new TransactionInfo();
        _transaction.setAmount(amount);
        _transaction.setType(type);
        _transaction.setUserName(userName);
        _transaction.setByAdmin(this.getM_user().getName());
        return this;
    }

    @Override
    public String GetRequestName() {
        return ADMIN_REQUEST_NAME.ADD_CHIP_FOR_USER_REQ;
    }

    public TransactionInfo getTransaction() {
        return _transaction;
    }

}
