//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player
package casino.cardgame.message.request.admin;

import casino.cardgame.entity.RoomInfo;
import casino.cardgame.entity.UserInfo;
import casino.cardgame.game_enum.RoomStatus;
import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.Timer;

public class CreateRoomRequest extends SFSGameRequest {

    private RoomInfo _room;

    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        String name = isfso.getUtfString("name");
        String displayName = isfso.getUtfString("display_name");
        String password = isfso.getUtfString("password");
        Double betchip = isfso.getDouble("bet_chip");
        Double smallBlind = isfso.getDouble("small_blind");
        Double bigBlind = isfso.getDouble("big_blind");
        int maxUser = (int) isfso.getDouble("max_user").intValue();
        Double minBuyin = isfso.getDouble("min_buy_in");
        Double maxBuyin = isfso.getDouble("max_buy_in");
        boolean noLimit = isfso.getBool("no_limit");
        String createBy = isfso.getUtfString("create_by");
        String status = RoomStatus.EMPTY;

        _room = new RoomInfo(name, password, displayName, maxUser, minBuyin, maxBuyin, noLimit, betchip, smallBlind, bigBlind, createBy, null, status, false);
        return this;
    }

    @Override
    public String GetRequestName() {
        return ADMIN_REQUEST_NAME.CREATE_ROOM_REQ;
    }

    public RoomInfo getRoom() {
        return _room;
    }
}
