//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.admin;

import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Timer;


public class GetListRoomRequest extends casino.cardgame.message.request.SFSGameRequest {
    
    private String _name;
    private int _index;
    private int _numRow;
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        _name = isfso.getUtfString("name");
        _index = isfso.getDouble("index").intValue();
        _numRow = isfso.getDouble("num_row").intValue();
        return this;
    }

    @Override
    public String GetRequestName() {
        return ADMIN_REQUEST_NAME.GET_LIST_ROOM_REQ;
    }

    public int getIndex() {
        return _index;
    }

    public int getNumRow() {
        return _numRow;
    }

    public String getName() {
        return _name;
    }
}
