//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.admin;

import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Timer;


public class GetTransactionRequest extends casino.cardgame.message.request.SFSGameRequest {
    private String _userName;
    private String _byAdmin;
    private String _fromDate;
    private String _toDate;
    private int _index;
    private int _numRow;
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        _userName = isfso.getUtfString("user_name");
        _byAdmin = isfso.getUtfString("by_admin");
        _fromDate = isfso.getUtfString("from_date");
        _toDate = isfso.getUtfString("to_date");
        _index = isfso.getDouble("index").intValue();
        _numRow = isfso.getDouble("num_row").intValue();
        return this;
    }

    @Override
    public String GetRequestName() {
        return ADMIN_REQUEST_NAME.GET_TRANSACTION_REQ;
    }

    public String getUserName() {
        return _userName;
    }

    public String getByAdmin() {
        return _byAdmin;
    }

    public int getIndex() {
        return _index;
    }

    public int getNumRow() {
        return _numRow;
    }

    public String getFromDate() {
        return _fromDate;
    }

    public String getToDate() {
        return _toDate;
    }
}
