//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetPlayerCardRequest.java
//  @ Date : 6/7/2012
//  @ Author : khoatd
//
//  @ Desc: Request to get card from the previous player



package casino.cardgame.message.request.admin;

import casino.cardgame.entity.UserInfo;
import casino.cardgame.entity.game.LevelDetailEntity;
import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.Timer;


public class UpdateLevelRequest extends casino.cardgame.message.request.SFSGameRequest {
    
    private LevelDetailEntity _level;
    
    @Override
    public SFSGameRequest FromSFSObject(ISFSObject isfso) {
        _level = new LevelDetailEntity();
        
        int id = isfso.getDouble("id").intValue();
        int level = isfso.getDouble("level").intValue();
        int levelType = isfso.getDouble("level_type").intValue();
        Double smallBlind = isfso.getDouble("small_blind");
        Double bigBlind = isfso.getDouble("big_blind");
        Double ante = isfso.getDouble("ante");
        int timeLife = isfso.getDouble("time_life").intValue();
        
        getLevel().setId(id);
        getLevel().setLevel(level);
        getLevel().setLevelType(levelType);
        getLevel().setSmallBlind(smallBlind);
        getLevel().setBigBlind(bigBlind);
        getLevel().setAnte(ante);
        getLevel().setTimeLife(timeLife);
        return this;
    }

    @Override
    public String GetRequestName() {
        return ADMIN_REQUEST_NAME.UPDATE_LEVEL_REQ;
    }


    public LevelDetailEntity getLevel() {
        return _level;
    }
}
