//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game;

import casino.cardgame.message.reponse.GAME_RESPONSE_NAME;
import casino.cardgame.message.reponse.RESPONSE_PARAMS_NAME;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;
import java.util.List;

public class GetListFreeUserResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private List<User> m_listUser; 
    
    public GetListFreeUserResponse() {
        super(GAME_RESPONSE_NAME.GET_LIST_FREE_USER_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        
        SFSArray sfsArray = new SFSArray();
        for(int i = 0; i< m_listUser.size(); i++){
            sfsArray.addUtfString(m_listUser.get(i).getName());
        }
        obj.putSFSArray("list_free_user", sfsArray);
        return obj;
    }

    public void setM_listUser(List<User> m_listUser) {
        this.m_listUser = m_listUser;
    }

}
