//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game;

import casino.cardgame.message.reponse.*;
import casino.cardgame.message.reponse.GAME_RESPONSE_NAME;
import casino.cardgame.message.reponse.RESPONSE_PARAMS_NAME;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;
import java.util.List;

public class InvitationReplyResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private int m_invitationReply; //0: ACCEPT; 1: REFUSE
    private String m_userReply;
    
    public InvitationReplyResponse() {
        super(GAME_RESPONSE_NAME.INVITATION_REPLY_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putInt("invitation_reply", m_invitationReply);
        obj.putUtfString("user_reply", m_userReply);
        return obj;
    }

    public InvitationReplyResponse setM_invitationReply(int m_invitationReply) {
        this.m_invitationReply = m_invitationReply;
        return this;
    }

    public InvitationReplyResponse setM_userReply(String m_userReply) {
        this.m_userReply = m_userReply;
        return this;
    }

}
