//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : Notify_Start.java
//  @ Date : 6/7/2012
//  @ Author : sangdn
//  @ Description : send init cards for each player
//
//
package casino.cardgame.message.reponse.game;

import casino.cardgame.message.reponse.*;
import casino.cardgame.message.reponse.GAME_RESPONSE_NAME;
import casino.cardgame.message.reponse.RESPONSE_PARAMS_NAME;
import casino.cardgame.message.reponse.game.tala.*;
import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.SFSArray;
import com.smartfoxserver.v2.entities.data.SFSObject;
import java.util.ArrayList;
import java.util.List;

public class InvitationResponse extends casino.cardgame.message.reponse.SFSGameReponse {

    private String m_userInvite; 
    private int m_roomId; 
    private String m_message; 
    
    public InvitationResponse() {
        super(GAME_RESPONSE_NAME.INVITATION_RES);
    }

    public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("user_invite", m_userInvite);
        obj.putInt("room_id", m_roomId);
        obj.putUtfString("message", m_message);
        return obj;
    }

    public InvitationResponse setM_userInvite(String m_userInvite) {
        this.m_userInvite = m_userInvite;
        return this;
    }

    public InvitationResponse setM_roomId(int roomId) {
        this.m_roomId = roomId;
        return this;
    }

    /**
     * @param m_message the m_message to set
     */
    public InvitationResponse setM_message(String m_message) {
        this.m_message = m_message;
        return this;
    }

}
