//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TableResultStatus.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.game_enum;


public enum TableResultStatus {
	WIN("WIN"),
	LOOSE("LOST"),
	DRAW("DRAW");
        
        protected String status;
        private TableResultStatus(String status){
            this.status = status;
        }
        public String getStatus(){
            return this.status;
        }
    
}
