//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TransactionStatus.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.game_enum;


public enum TransactionStatus{
	PENDING("pending"),
	CANCEL("cancel"),
	COMPLETE("complete");
        
        private String status;
        private TransactionStatus(String status){
            this.status = status;
        }
        public String getStatus(){
            return this.status;
        }
}
