//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : TransactionType.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.game_enum;


public enum TransactionType {
	DEPOSIT("deposit"),
	WIDTHDRAW("widthdraw");

        private String type;
        
        private TransactionType(String type){
            this.type = type;
        }
        public String getType(){
            return type;
        }
}
