//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : UserStatus.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.game_enum;


public class UserStatus {
	public static String PLAYING = "playing";
        public static String WAITING = "waiting";
        public static String OFFLINE = "offline";

}
