//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : UserTitle.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.game_enum;


public class UserTitle {
	public static String NORMAL = "Normal";
	public  static String POWER = "Power";
	public  static String VIP = "VIP";
	public static  String LEVEL1 = "level 1";
	public static  String LEVEL2 = "level 2";
	public static  String LEVEL3 = "level 3";
	public static  String LEVEL4 = "level 4";
	public static  String LEVEL5 = "level 5";

}
