//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GAME_RESPONSE_NAME.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.reponse;


public class GAME_RESPONSE_NAME {
	public static String EXCEPTION = "exception_res";
	public static String REGISTER_RES = "reg_res";
	public static String REGISTER_ERROR_RES = "reg_eror_res";
	public static String GET_TRANS_BY_USER_RES = "get_trans_by_user_res";
	public static String GET_LOGIN_INFO_RES = "login_info_res";
	public static String GET_USER_INFO_RES = "get_user_info_res";
        public static String GET_TOP_WINNER_RES = "get_top_winner_res";
        public static String GET_LEADER_BOARD_RES = "get_leader_board_res";
        public static String CHARGE_CARD_RES = "charge_card_res";
        public static String GET_LIST_FREE_USER_RES = "get_list_free_user";
        public static String INVITATION_RES = "invitation_res";
        public static String INVITATION_REPLY_RES = "invitation_reply_res";
}
