//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetLoginHistoryResponse.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.reponse;

import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.ISFSObject;


public class GetLoginHistoryResponse extends SFSGameReponse {

   public GetLoginHistoryResponse(){
       super(GAME_RESPONSE_NAME.GET_LOGIN_INFO_RES);
   }
}
