//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : GetUserInfoResponse.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.reponse;

import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.ISFSObject;


public class GetUserInfoResponse extends SFSGameReponse {

   public GetUserInfoResponse(){
       super(GAME_RESPONSE_NAME.GET_USER_INFO_RES);
   }
}
