//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : RegisterResponse.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//



package casino.cardgame.message.reponse;

import com.smartfoxserver.v2.entities.User;
import com.smartfoxserver.v2.entities.data.ISFSObject;
import com.smartfoxserver.v2.entities.data.SFSObject;


public class RegisterErrorResponse extends SFSGameReponse {

    private String _mesage;
    public RegisterErrorResponse(){
       super(GAME_RESPONSE_NAME.REGISTER_ERROR_RES);
    }
    
     public SFSObject ToSFSObject() {
        SFSObject obj = new SFSObject();
        obj.putUtfString("message", _mesage);
        return obj;
     }

    public void setMesage(String mesage) {
        this._mesage = mesage;
    }
}
