//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : casino project
//  @ File Name : IServerController.java
//  @ Date : 5/27/2012
//  @ Author : sangdn
//
//
package casino.cardgame.controller.server;

import casino.cardgame.message.event.SFSGameEvent;
import casino.cardgame.message.request.SFSGameRequest;
import com.smartfoxserver.v2.exceptions.SFSLoginException;

public interface IServerController {

    public void HandleAdminMessage(SFSGameRequest sfsreq);

    public void HandleGameMessage(SFSGameRequest sfsreq);

    public void HandleUserLogin(SFSGameEvent sfse) throws SFSLoginException;

    public void HandlePlayerToSpectator(SFSGameEvent sfse);

    public void HandlePrivateMessage(SFSGameEvent sfse);

    public void HandlePublicMessage(SFSGameEvent sfse);

    public void HandleRoomAdded(SFSGameEvent sfse);

    public void HandleRoomRemove(SFSGameEvent sfse);

    public void HandleRoomVariableUpdate(SFSGameEvent sfse);

    public void HandleSpectatorToPlayer(SFSGameEvent sfse);

    public void HandleServerReady(SFSGameEvent sfse);

    public void HandleUserDisconect(SFSGameEvent sfse);

    public void HandleUserJoinRoom(SFSGameEvent sfse);

    public void HandleUserLeaveRoom(SFSGameEvent sfse);

    public void HandleUserLogOut(SFSGameEvent sfse);

    public void HandleUserVariableUpdate(SFSGameEvent sfse);

    public void HandleUserJoinZone(SFSGameEvent joinZoneEvt);
}
